### ISSUE TITLE
Don't upload to keyservers

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#1]
over in https://github.com/autocrypt/inbome/issues/7 @keks wrote:

> Unfortunately there is no way to signal to keyservers that a key should not be accepted for upload. As soon as this is possible we should adopt that mechanism.

I'm transferring that issue to this repo so we can close down the old inbome repo.

**Comment by Valodim** [comment]
Related

https://lists.nongnu.org/archive/html/sks-devel/2016-12/msg00025.html

**Comment by Valodim** [comment]
just pung the thread, I really hope we can get this sorted out.

**Comment by pbrunschwig** [comment]
By using UUID instead of email addresses, uploading to keyservers is made unuseful. The spec cares for this.

**Comment by Valodim** [comment]
Use of UUIDs is not mentioned in the spec, in fact we recommend placing the user's address in the user id.
