### ISSUE TITLE
typo in "Example Data Flows and State Transitions" page

### ISSUE THREAD

**Issue by bford** [autocrypt/autocrypt#128]
First paragraph: "will may then be encrypted” - is it “will” or “may”?  

https://autocrypt.readthedocs.io/en/latest/examples.html

(Pretty minor issue I know. :)  Just catching up after DKG pointed out this project to me, and hope to have more substantial feedback soon...)

**Comment by Valodim** [comment]
It's "may", methinks. I fixed the typo :)
