### ISSUE TITLE
Move test data to a separate repository

### ISSUE THREAD

**Issue by cketti** [autocrypt/autocrypt#131]
Right now both the py-autocrypt and the go-autocrypt repository contain test emails with `Autocrypt` headers. Unfortunately, currently at least the ones in go-autocrypt are outdated and don't match the spec.

It'd be nice if there was a central place where authoritative test messages lived. I'd be happy to create a PR  to copy and clean up the current test data if someone created a repository.

**Comment by Valodim** [comment]
sounds good :+1:

**Comment by hpk42** [comment]
yep, +1 for a dedicated repo with a "level1" directory of test mime messages that explain in their bodies how a MUA is to handle them.  Hum, or maybe we make that part of the "spec" repository?  We could then link to it easily from the spec and it's easier to see the cross-relation.  In py-autocrypt i'd then copy that directory in and make it part of py-autocrypt repo again.

**Comment by juga0** [comment]
>  In py-autocrypt i'd then copy that directory in and make it part of py-autocrypt repo again.

Every time that the data repo would change would not be automatically updated with the data in go-autocrypt and py-autocrypt, but we can see to solve data with git submodule or similar.

To be able to close this issue, i've created the repo https://github.com/autocrypt/specs_data with the current data in https://github.com/autocrypt/py-autocrypt/tree/master/core/tests/data.

AFAIK, we don't currently have any mention of that data in the specs, but would be great to add it now that it is a repo created just for that.

**Comment by dkg** [comment]
I'm wondering whether we want this as a separate repository or not.

If we make it part of the main "Autocrypt" repository, then we can try to make sure that updates to the spec are accompanied by updates to the examples.
