### ISSUE TITLE
Import Memory Hole specs into autocrypt

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#134]
[Memory Hole protected mail headers](http://modernpgp.org/memoryhole/specs/) are currently hosted in the ModernPGP github group.  I think we should move that specification over to the autocrypt group, since that's the place where it is most actively discussed.

**Comment by hpk42** [comment]
the link to modernpgp is now broken -- maybe there should be a redirect to a page on autocrypt.org which explains its current status?  The move was a bit rush i think -- the landing page on autocrypt.org should have been there first, currently it feels a bit like it's just dumped on the github autocrypt org without anyone caring to explain its status, folks involved so far and potential relations to future autocrypt specs.

**Comment by varac** [comment]
I get a timeout for this link, please make the content of that site available for the public soon, it would be nice to point ppl to a working website.

**Comment by dkg** [comment]
This is now being worked on as an independent document at https://github.com/autocrypt/protected-headers -- we hope to incorporate it by reference in a future version of the autocrypt spec.
