### ISSUE TITLE
Can Autocrypt-Gossip headers appear in cleartext mail?

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#135]
level1 currently says:

```
An Autocrypt MUA MAY include ``Autocrypt-Gossip`` headers in messages
with more than one recipient. These headers MUST be placed in the root
MIME part of the encrypted message payload. 
```

Are Autocrypt-Gossip headers only supposed to be encrypted messages, or can they be in cleartext messages?  if they can be in cleartext messages, should they be treated differently than headers in encrypted messages?

**Comment by Valodim** [comment]
Gossip headers can only appear in the payload of an encrypted message, I guess that should be more clearly stated in the first sentence.

As stated, the goal of gossip headers is to ensure replies to encrypted group mails can also be encrypted in all cases. Including those headers in unencrypted mails would not further this goal, while leaking more data.

**Comment by dkg** [comment]
Thanks for the explanation, i agree that it should be more clearly stated.  In particular, a statement that an MUA MUST ignore Autocrypt-Gossip: headers in a cleartext message would probably be helpful.

**Comment by hpk42** [comment]
Wouldn't it help opportunistic overall encryption if i would gossip the keys i know in a clear text mail?  With e.g. Delta one has idea and no UI for finding out which keys i have.  For L1 closure i am fine, however, to simply go with dkg's suggestion and be done with it for now.

**Comment by Valodim** [comment]
That doesn't seem like a "MUST" to me: the protocol works perfectly fine even if some implementation decides to include or parse Autocrypt-Gossip headers in the outer body (which is basically what holger is suggesting, too). I'm good with a SHOULD yo.

So far I'm not in favor of plaintext gossip. It just seems one step too far while we don't have a good feeling for how well our key choice mechanism actually performs in practice.

**Comment by dkg** [comment]
I'm not super happy about leaving it up to arbitrary implementations to do arbitrary things, and would like to have some fairly strong guidance.  In particular, this is important because i want someone using two different autocrypt-capable MUAs to expose the same experience to the user about who they can encrypt to and who they cannot.  If one MUA does something radically different from the other, then it's more inexplicable behavior for the user, which is what we're trying to avoid.

**Comment by Valodim** [comment]
I agree with all of that. Still, a "MUST" doesn't seem appropriate to me. I don't think an implementation that really wants to have gossip in plaintext mails would be deterred by a MUST more than a SHOULD, it would just make their implementation non-compliant by definition rather than different in terms of a SHOULD. Worst case, they would add an independent unstandardized mechanism for key gossip.

Anyways this is just my intuition, I'm not particularly attached to it. Anybody else have some thoughts on this?

**Comment by dkg** [comment]
even a "SHOULD ignore" would be better than what is there currently, so i'd be happy to take that, and then we can talk separately about whether to s/SHOULD/MUST/
