### ISSUE TITLE
is the `type=` parameter always going to be an integer, or could it be a string?

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#136]
since we moved from `type=p` to `type=1` i'm now trying to decide whether an Autocrypt toolkit in a strongly-typed language should treat the parsed type value as an integer instead of a string.

I'm leaning in the direction of an integer (non-integer values would be forbidden), personally, because i don't want there to be too many types.

How do others feel about this choice?

We should be clear about it one way or the other in the spec, though.

**Comment by Valodim** [comment]
All other parameters are strings, I don't see a strong need for introducing an int type. Implementations need to handle "type=x" without blowing up one way or another. Versioning in strings also means that they can only be tested for equality, not relative ordering. "I support autocrypt types 1 and 2" sounds somehow better to me than "I support autocrypt version 2 or earlier"

**Comment by dkg** [comment]
For C implementations, knowing that something is going to be an int makes it much easier to deal with -- no memory allocation issues if we get to use a primitive type :)

If someone sends a C implementation that can only deal with ints an "Autocrypt: type=x" , then the whole header will get ignored as an unknown type (which is probably correct behavior).

I agree that implementations will need to know explicitly about the types they support, not some sequence of types.  but my takeaway from that is that sticking to ints will create a strong incentive to minimize the number of types we allow to exist.  Fewer types == better interop :)

**Comment by hpk42** [comment]
I can see:

- how restricting to int simplifies c-style impls
- restricting ourselves to type=[int] provides clarity of what the values mean 

As autocrypt is catching on i think it's crucial to think about post-L1 spec releases.  What if after "level 1 closure" we modify some things in a backward compatible way?  We don't want to release this as "type=2" i guess.  

A classical way would be to have two numbers ("major", "minor").  You can ignore minor but you must look at "major" -- if you don't support major=2 but only major=1 you must ignore the header.  I'd be fine with encoding this "X.Y" and that X and Y must be integers.   I think having two numbers provides enough flexibility and constraint (i.e. going for third "Z" number aka SEMVER versioning is overdoing it for a spec -- also we can have a 1.0.5 release tag on the web page without the ".5" appearing in the type value.

**Comment by dkg** [comment]
We can get rid of this, now that we got rid of the type parameter.
