### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by comradekingu** [autocrypt/autocrypt#137]
![autocrypt](https://user-images.githubusercontent.com/13802408/31706293-c7d6b21a-b3e8-11e7-9472-c81b0a1f0290.png)
![autocrypt2](https://user-images.githubusercontent.com/13802408/31706302-cdbd85dc-b3e8-11e7-9db3-45a15ef42655.png)

**Comment by dkg** [comment]
what does this issue mean?

**Comment by comradekingu** [comment]
@dkg It means I made a logo for Autocrypt. Even if most everything happens out of sight like SSL, it is worthwhile to communicate a level of familiarity the user can trust to be Autoencrypt-ion.

**Comment by dkg** [comment]
Thanks for working on a logo!  I can't see it at all in this web page, i'm afraid.  (your first comment looks blank to me).   Is [this](https://user-images.githubusercontent.com/13802408/31706302-cdbd85dc-b3e8-11e7-9db3-45a15ef42655.png) it?

Are you aware of the other autocrypt logo work that has been done? You might want to look at the [discussion on the mailing list](https://lists.mayfirst.org/pipermail/autocrypt/2017-June/000139.html).

 * [some example logos from that discussion](http://lists.mayfirst.org/pipermail/autocrypt/attachments/20170609/101a684b/attachment-0001.pdf)
 * [a variant based on U-locks (for bicycles)](http://lists.mayfirst.org/pipermail/autocrypt/attachments/20170619/ce42c8aa/attachment.pdf)

**Comment by comradekingu** [comment]
@dkg I think we've gone full circle on new user old user. But yes, I think. Would explain what it was, but I don't like doing that. Black lines on white background in any event.
Was not aware of any such effort. I will try to muster up the courage to mailinglist it. After I dare to go to sleep.

Girls with laughable salads woes
anything goes, wrong, uncomitted git
dkg says: "is this it"?
[Overhead the albatross hangs motionless upon the air, intensify]

**Comment by dkg** [comment]
Thanks for the contribution.  We had a discussion around logos at the autocrypt meeting this weekend, and we included your logo in the discussion.  We've gone with a different logo design, though, and we'll be publishing it soon.

**Comment by hpk42** [comment]
after more discussions at the still ongoing Autocrypt gathering, we are in the process of going for the u-lock variant that @dkg linked. Thanks for your suggestions, i kind of like aspects of them :)

**Comment by comradekingu** [comment]
Sadly I have a dog in the race, but it bears to mention the u-lock has caught mindspace for being used as a weapon lately.
