### ISSUE TITLE
What should a receiving client do when there is more than one address in From: ?

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#138]
Consider the following E-mail with multiple senders:

```
Date: Mon, 23 Oct 2017 01:19:16 -0400
Subject: strange messages
To: carol@example.net
From: alice@example.net, bob@example.net
Autocrypt: addr=alice@example.net; keydata=AOYM2nmg2sa83+/...
Content-Type: text/plain

hi there
```

This appears to be legitimate syntax.

So the questions raised are, when Carol's autocrypt client parses this message:

 * does it accept this e-mail as having a valid header for `alice@example.net`?
   * if not (because `addr=` doesn't match the actual addresses found in `From:`), then does it count as having *no* header for `alice@example.net`?  (that is, does it set the state for `alice@example.net` to `reset`?)
 * does it accept this e-mail as *not* having a valid header for Bob? (that is, does it set the state for `bob@example.net` to `reset` ?)

I see two possible sensible options:

Ignore messages with multiple `From:`
-------------------------------------------------

For simplicity's sake, and to avoid Alice's being able to clear Carol's belief about Bob's Autocrypt state simply by adding `, bob@example.net` to `From:` during message sending,  we could say that this message should be ignored entirely for Autocrypt parsing (affecting neither state).

Update autocrypt state for both senders
---------------------------------------------------

For consistency's sake, and banking on the same "we do not defend directly against active attacks", we could say that this message should update Carol's representation of both Alice and Bob's state: `reset`ting `bob@example.net`, while updating `alice@example.net` with the new `keydata`.

It's conceivable that there are some sending relays (combined with DMARC and DKIM) that would accept this outbound mail if *either* alice or bob was sending it, which would mean that people within that domain could reset each other's Autocrypt state on external parties, even though DMARC, DKIM, and authentication requirements were already in play that might limit this kind of interaction.

This is a nasty corner case, but we should probably state an explicit expectation here.

**Comment by Valodim** [comment]
Do you have an example of where this case actually occurs? I'm not sure I've ever seen multiple message authors.

My guy feeling is to ignore such mails for autocrypt purposes, or at least avoid *any* complexity in the handling.

**Comment by dkg** [comment]
i don't know that i've ever received such a message that wasn't from a perverse test suite.  however, at least some MIME libraries (i've been working with GMime) do return a list of From addresses, rather than zero-or-one From address.

The complexity in handling the update logic doesn't seem particularly high -- you just get one Autocrypt record to process per From: address, and you do them in sequence (or in series).

I'm inclined to go with "Update autocrypt state for both senders" as the recommendation, but i don't think i'd blame any implementer for ignoring multi-from messages entirely for the purposes of updating Autocrypt state.  Still, it's probably worth documenting this corner case somewhere so that implementers aren't surprised by it.  I was surprised when i ran into it designing an Autocrypt API for GMime.

**Comment by hpk42** [comment]
A "test suite" does not count as a real use case IMO.   I've never seen multipe From's either. So i also think that just ignoring the situation is good enough for now and the easiest to implement as it just ties into typically one code place (that already exists) which detects conditions under which to ignore a mail wrt autocrypt headers.

**Comment by azul** [comment]
Just checked with @hpk42 and it looks like I can send such an email with thunderbird and it will arrive in his inbox and mutt will hapilly reply to both senders.
