### ISSUE TITLE
document (lack of) interaction with `Sender:` and `Reply-To:` fields

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#139]
[RFC 5322 discusses three types of originator](https://tools.ietf.org/html/rfc5322#section-3.6.2):
 * `From:`
 * `Sender:`
 * `Reply-To:`

At the moment, Autocrypt appears to focus specifically on matching the `addr=` attribute to the `From:` address. 

If we expect implementers to ignore `Sender:` and `Reply-To:` we should probably state that explicitly for completeness.  This probably doesn't need more than a sentence of justification.

**Comment by Valodim** [comment]
Agreed.
