### ISSUE TITLE
Specify people should use identity keys consistently

### ISSUE THREAD

**Issue by azul** [autocrypt/autocrypt#140]
In theory the spec currently allows for sending different keys with every email. The only way we somewhat restrict that is [in context of multi client](https://autocrypt.org/en/latest/level1.html#avoiding-client-conflicts).

I think we should specify that people should stick to one identity key and send it to everyone. They can do fancy things with their encryption keys if they want. But for gossip and eventually warning about key change ("Bob has got a new autocrypt number...") it would be really good if people would stick to their identity keys unless they loose them.

I would like for autocrypt to have a 1 on 1 mapping between email address and identity key at a given time. Happy to hear about usecases that require something else though.

**Comment by dkg** [comment]
i agree that this is a reasonable suggestion.  I don't think that any implementor who is thinking about the interop with a bunch of clients behaving this way will do anything different.  But it's worth writing it down for those implementors who don't want to think too much :)
