### ISSUE TITLE
Autocrypt header: not clear whether type=1 is an optional or a mandatory attribute

### ISSUE THREAD

**Issue by juga0** [autocrypt/autocrypt#141]
When reading https://github.com/autocrypt/autocrypt/blob/master/doc/level1.rst#L123, ``[`` suggests ``[type=1]`` is an optional attribute. However reading https://github.com/autocrypt/autocrypt/blob/master/doc/level1.rst#L131 and below, gives the impression that this attribute is mandatory.

**Comment by Valodim** [comment]
What gives you that impression? Lines 133 and 134 state that the parameter defaults to `type=1`. Is it the "for now the only supported type" part?

**Comment by juga0** [comment]
I think so, also because right before it says "The ``type`` and ``keydata``" and ``keydata`` is mandatory. Maybe we could just clarify at the beginning or there which are mandatory and optional attributes?.

**Comment by hpk42** [comment]
added #142 to clarify that "Autocrypt header section".
