### ISSUE TITLE
document "Autocrypt-friendly" MUAs

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#16]
We might want some sort of mechanism for an MUA that isn't Level 0 compliant, or that is level 0 but is not the claiming MUA for a given mailbox, to be able to say "i don't do autocrypt here, but please don't send cleartext to this account just because you see mail from me!"

The simplest way would be that the MUA could send something like:

    Autocrypt: ignore

which would just skip the update of the Autocrypt internal state entirely.

I'm calling this "Autocrypt-friendly", but it needs careful consideration, because Autocrypt actually relies on non-compliant clients sending an effective "reset" (via e-mail that has no `Autocrypt:` header).  So if every non-Autocrypt client just started sending `Autocrypt: ignore`, we'd end up with un-expiring keys from a single throwaway use of an Autocrypt-capable client.

**Comment by Valodim** [comment]
Can you elaborate on what would be the advantage of this? We already have a setting to enable or disable the fallback, using "prefer-encrypt: yes" in the autocrypt MUA. If it has to be enabled by the user, they might just as do it in the autocrypt MUA. Otherwise, it sort of defeats the purpose of the fallback mechanism?

**Comment by dkg** [comment]
@Valodim wrote:
> We already have a setting to enable or disable the fallback, using "prefer-encrypt: yes" in the autocrypt MUA

I don't think that `prefer-encrypt=yes` will disable the clearing of state when receiving an e-mail with no `Autocrypt` header at all, unless i'm misunderstanding something.

Consider a user Alice with two MUAs, an Autocrypt-capable one "C" (that has claimed the mailbox) and a potentially Autocrypt-friendly one "F" (maybe it's even Autocrypt-capable, but just knows it hasn't claimed the mailbox).

Alice's typical workflow is to send mail to Bob from whichever MUA she happens to be using, and she has left all settings at their defaults.

Without the capacity for `Autocrypt: ignore`, messages from F have no `Autocrypt` header at all.

As a result, when Bob sends mail to Alice, the Autocrypt recommendation varies between `disable` and `available` depending on the last MUA Alice used to mail Bob.  This is potentially mysterious to Bob, if there is any visible difference between these states (such as the "Encrypt" button being greyed out or not).

It gets worse if Alice sets `prefer-encrypted=yes` in "C" -- in that case, Bob's MUA changes its Autocrypt recommendation on new mails to Alice between `disable` and  `encrypt`.

If F could tell that C has claimed the mailbox and updated their claim not too long ago, it would be nice for F to be able to say "hey, that Autocrypt header you might have seen from me on previous e-mails is still OK, even though i'm currently sending you cleartext mail from a different client"

Does this make sense or have i misunderstood the level 0 spec?

**Comment by pbrunschwig** [comment]
The spec takes care of this.
