### ISSUE TITLE
autocrypt peer state is ambiguous about handling corner cases

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#165]
the current "Updating Autocrypt Peer State" section is ambiguous about states where (for example) two autocrypt headers arrive in one message, but one of them matches the From: header and one of them does not -- what should happen?  what does "valid" mean in this context?

@Valodim and i were arguing about this and we actually implemented it in different ways :/

**Comment by azul** [comment]
What we are saying so far in the spec is
```
The addr attribute is mandatory and contains the single recipient address this header is valid for. In case this address differs from the one the MUA considers the sender of the e-mail in parsing, which will usually be the one specified in the From header, the entire header MUST be treated as invalid.
```

So in the case outlined above the one header MUST be treated as invalid. We therefore only have one valid header. The spec does not say anything about that case. It says:
```
If there is more than one valid header, this SHOULD be treated as an error, and all Autocrypt headers discarded as invalid.
```

It does not explicitly state how to proceed with one valid header... but i think it's clear from the context we expect it to proceed.

**Comment by azul** [comment]
@Valodim dkg said you have a different interpretation of this / your code behaves differently. Do you think we should open the discussion about the behaviour or make the spec more clear?

**Comment by Valodim** [comment]
No, the spec is clear enough. My code for this dates back to our December meeting last year, so I likely just had a different understanding than what ended up in the spec. I'm fine with this interpretation of "valid", even though I think the situation with multiple headers for different addresses is always fishy and treating it as an error would be a more defensive way of dealing with it.

If we want to pin this down better, unit tests seem like a good option.

**Comment by dkg** [comment]
So, can we close this issue, or can we at least remove it from the level 1 milestone?
