### ISSUE TITLE
set HSTS header on https://autocrypt.org

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#17]
Autocrypt is a security mechanism, and it shouldn't use cleartext http.

We should serve an HSTS header on https://autocrypt.org/

For example:

      Strict-Transport-Security: max-age=63072000; includeSubDomains; preload 

Once we're serving this, we can submit it to the hsts preload list here: https://hstspreload.org/

**Comment by dkg** [comment]
(this is low prioirity, but something that we should just have taken care of before we accidentally accumulate any cleartext cruft)

**Comment by dkg** [comment]
I'd fix this if i had access to the nginx configuration -- it should be [a single line in the nginx config](https://www.nginx.com/blog/http-strict-transport-security-hsts-and-nginx/):

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

**Comment by hpk42** [comment]
I think i have successfully enabled HSTS  and have also registered it with the https://hstspreload.org website.  they say it's eligable and queued.  i think we can close this unless we want to be super-dilligent and monitor that it actually gets included .... (i think that's overdoing it).

**Comment by dkg** [comment]
yep, thanks for making this fix!
