### ISSUE TITLE
Describe in more detail why Autocrypt Setup Message won't work for multiple aliases on a single account

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#178]
The text as written says that the Autocrypt Setup Message won't work when using different keys for multiple aliases.  But it's not clear to me why that's the case, as each distinct Setup Message could have a different From/To address that distinguishes it from another.

**Comment by Valodim** [comment]
Having more than one key in a setup message will necessarily mean one of those keys is not in both the From and To header. While it might be nice to transfer more than one account this way, allowing this could introduce security problems, so I would just conservatively say we don't support it at this point.

**Comment by dkg** [comment]
But we don't need to have multiple keys in the setup message.

If you treat an alias as a separate account, then there will only be one key in the Autocrypt Setup Message that is addressed To and From the address associated with that alias.

**Comment by dkg** [comment]
PR #203 is intended to address this issue
