### ISSUE TITLE
Rewrite updating autocrypt peer state to be easier to parse

### ISSUE THREAD

**Issue by azul** [autocrypt/autocrypt#179]
https://autocrypt.readthedocs.io/en/latest/level1.html#updating-autocrypt-peer-state

Separate three steps:
* update last_seen if effictive date is newer
* update last_seen_autocrypt if header is present and effective date is newer
* set state according to value in header or reset if there is no header.

**Comment by Valodim** [comment]
Is this still a thing?

**Comment by azul** [comment]
#209 now handles this...
