### ISSUE TITLE
Clarify that "level 0" is about guaranteeing a user experience, not the smallest possible interesting featureset

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#18]
I've heard from some MUA developers that they felt blind-sided by the "level 0" terminology.  they were thinking that "level 0" would be something like the smallest possible feature set to be interesting to a developer.

Instead, i think the autocrypt project sees "level 0" to be the smallest possible feature set to be interesting to a *user*, while it contains several different moving pieces that a developer might want to consider individually (and might individually provide some actual value in an MUA targeted toward more-sophisticated users) in the classic "divide and conquer" approach to implementation.

I don't think we should change the "level 0" concept -- i think it's important that autocrypt stays user-focused.  But it'd be nice to communicate this better to developers so that they don't feel confused or surprised by the change of focus.

**Comment by hpk42** [comment]
IMO makes sense to clarify that level0 design is mainly driven by usability perspectives.
