### ISSUE TITLE
chatbot to proxy github updates into #autocrypt on freenode

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#19]
several autocrypt folks are hanging out in ``#autocrypt`` on irc.freenode.net -- it'd be great to have a bot set up that links activity on this repo into that chat channel.

**Comment by dkg** [comment]
hm, there already is something like this (user "GitHub92" as of right now), but it doesn't seem to notice the creation of new issues...

**Comment by hpk42** [comment]
also the github chat bot is very unreliable.  Note that we can run a (at best systemd-controlled) process on autocrypt.org to react to github webhooks which ASFAIK work reliably and can be debugged.  My search for good available such chat-bot proxies did not yield anything satisfying so far.  There is a "trumpet" project i am using on another VM with configuration in a json file -- but it doesn't handle issues and i am not sure it's maintained much. 

any ideas anyone for github-webhook reacting chatbot projects?

**Comment by gfa** [comment]
What about [supybot-github](https://github.com/kongr45gpen/supybot-github)?
it looks maintained and supports commits and github issues.

its a plugin for supybot or its fork limnoria, both are maintained in debian 

I could give it a try, i have a machine where i can run it i'd just need someone to setup the github hooks and api keys

**Comment by dkg** [comment]
@gfa -- if you have a machine where you can run it, i'd be happy to try to handle the github hooks and whatnot.  just let me know what you need.

**Comment by hpk42** [comment]
Really looking forward to a richer and more reliable github bot. @gfa you might run the bot under some account at the VM that hosts web and MX of autocrypt.org -- send a mail to admins at lists.codespeak.net if that makes sense to you, with your ssh-public key and the suggested accountname. Once it works we can figure out systemd integration and version control of the config (the VM versions files in /etc ).

**Comment by gfa** [comment]
I prefer to use my vm, because is already configured ;)
if apache, letsencrypt, and systemd can be configured on the MX I dont mind moving the bot.

the vm i'm using is a GCE always free i have without use

When I get home I'll add to this ticket the token that needs to setup the webhook and configure to bot to send msgs to #autocrypt channel

**Comment by gfa** [comment]
Now the Github hooks have to  be configured to contact the bot, the url and token are in /etc/ghbot/secrets on the VM

Once the webhooks are configured in github notification will start to flow on #autocrypt

**Comment by gfa** [comment]
Its done now

**Comment by gfa** [comment]
Its done now
