### ISSUE TITLE
Disaster Recovery

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#2]
Over at https://github.com/autocrypt/inbome/issues/4, @Valodim wrote the following note.  I'm transferring it over here so we can close down the "inbome" repository.

People lose devices, people forget passwords. Some scenarios and thoughts:

* Device is lost, no precautions at all

This is a bad case, because it leaves us with
a) unreadable mail, forever
b) more unreadable mail from peers with established INBOME negotiation

Not much we can do here I guess, other than regenerate and hope the user doesn't abandon crypto? I'm not sure "send mail to all users we established crypto with" is such a good idea... We should avoid this scenario by all possible means!

* Device is lost, no backup

In this case, the issue a) is a lost cause by design. We can help issue b) along if we were able to store a revocation certificate somewhere along the way.

Revocation certificates are not of very high value (they only help for denial of service attacker capability, and that's achievable without them), so we can store them in the user's mailbox in plaintext, then publish it when we regenerate keys. This requires a distribution mechanism of course, which is solved in pgp using keyservers, *if* we can assume everyone to update keys every few days, or before use.

* Device is lost, but there is a backup

This is the scenario we should try to be in. So we should automate, as much as possible!

General idea: Make a backup of secret key material in the user's mailbox, which is encrypted with a high-entropy backup code that is left with the user. (see [relevant document](https://github.com/autocrypt/autocrypt/blob/master/doc/multi-device.rst))

(Just brainstorming: Another possible option would be to hand the user the random seed used for generating all key material, so we wouldn't even need to store anything ("offline backup"). But that is a dangerous route, requires a deterministic PRNG implementation on all platforms, and is also something we can only do at key setup)

**Comment by meskio** [comment]
I think will be useful to have _shortish_ expiration date in the keys. If we lost access to the private key our contacts will discard this key once expired and accept the new one we are sending them. autocrypt clients should extend the expiration date automatically and accept updates of expiration dates (over the autocrypt header or other refresh mechanisms).

I like this more than leave a revocation certificate unencrypted hanging around. An attacker could use our revocation certificate to invalidate our key, create a new key and send it to all our contacts. The attacker could even build up a MitM attack by reencrypting everything to our key so we don't notice it.

Even if we have a backup mechanism we need a recovery mechanism for the case where the backup can't be accessed. For example the user might lost the backup code.

**Comment by dkg** [comment]
The trouble with a shortish expiration date on the keys is that people will lose the ability to encrypt to a peer if they don't receive mail regularly from that peer.  Is this a property that we want?  It seems in opposition to the goals of Autocrypt.

**Comment by azul** [comment]
We have defined a mechanism to symmetrically encrypt the private key and send it to ones own mail account. This is mainly planned as a transfer mechanism between devices but can also be used as a key backup.
I think this is our answer to disaster recovery for Level 1. Will close this issue. We can have a new issue for better ideas for Level 2 later on.
