### ISSUE TITLE
need to define lockout

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#20]
the "lockout" link in doc/level0.rst  doesn't appear to work. -- the "lock out" text in https://autocrypt.readthedocs.io/en/latest/level0.html points to https://autocrypt.readthedocs.io/en/latest/lockout

also, we just haven't defined it clearly.

Someone should take a stab at making a complete definition, so we have something concrete to fine-tune.

**Comment by dkg** [comment]
ok, the lockout links do seem to work now :)

but we still need to define the lockout process specifically.

**Comment by Valodim** [comment]
Repeating #30 here to keep things in one place:

The approach for lockout that I, and probably most others, had in mind is to check whether a lockout mail is there before generating a key, if not generate a key, then put the lockout in the mailbox right after.

I noticed during implementation that this is really not easy to do, because the logic for imap - as is the case for k9 - might be far away from the code that deals with creation of identities. It also turns key creation into an operation that requires connectivity.

This mechanism can roughly be described "do A, then B, then C in immediate succession" where A and C are imap check and put operations. Loosening this to "do A and C when convenient, do B best effort inbetween" is more in line with the way email clients would naturally deal with A and C, which is in a background routine that takes care of synchronization.

**Comment by Valodim** [comment]
While sitting down to write the spec, I realized that any claim made can be advisory at best - if a user changes devices, they need to be able to override a claim. It's also relatively easy to detect other active autocrypt clients simply by scanning the outbox for autocrypt headers, no special directory needed.

This brings up the question, is the complexity worth it? I don't think so. Even telling the user "careful, you can only have one autocrypt client!" during setup would not be much worse compared to the advisory claim.

**Comment by Valodim** [comment]
note for later: if we do do imap sync at some point, it might be worth publishing a simple informative rfc similar to https://tools.ietf.org/html/rfc5785 to establish a `_well_known` mailbox

**Comment by BjarniRunar** [comment]
FWIW, I really like the idea of detecting autocrypt headers in the outbox (or elsewhere in mail determined to be "from me") as a mechanism to implement lockout / or otherwise detect/handle "collisions" with other AutoCrypt clients on the same account. Since it abstracts the mail transfer away completely, it may work in weird cases we haven't even thought of yet, unlike the explicit IMAP-base lockout (which fails trivially for users using POP).

**Comment by dkg** [comment]
this assumes that each client knows where the outbox is, though.

I've used several clients that each have their own idea about where to store "sent" mail, and i've used clients that don't store sent mail at all, or just store it in the inbox.

So if we're going to require some sort of standard for where outbound mail gets placed, then we might as well specify the standard for where to place the lockout (and not require any other changes to the existing logic of an MUA, like disallowing the user to choose an alternate sent-mail folder if the account is autocrypt-enabled)

**Comment by dkg** [comment]
fwiw, i also agree with @Valodim that the claim has to be explicitly overridable, at least in level 1.  I'd be fine with "level 0" requiring manual hackery to override a claim ("go into your imap folders, look for `_well_known`, and delete any mail you find there")

**Comment by dkg** [comment]
Also, specifying a concrete location for autocrypt lockout is a good first-step toward preparing clients to be able to do cross-device sync, which we will want for level 1.  So omitting it on level 0 leaves us with a heavier ask for agents transitioning from level 0 to level 1.

**Comment by Valodim** [comment]
The 'sent' folder is one of the actually defined special folders in imap (see [rfc6154](https://tools.ietf.org/html/rfc6154)), are there practical problems with recognizing the sent box that I am unaware of?

**Comment by BjarniRunar** [comment]
@dkg: You don't need to scan for outbound mail in particular. We're already mandating that any newly discovered (incoming) mail have its headers parsed for AutoCrypt headers to create state. Some of that newly discovered mail may be in a "sent" folder - the AutoCrypt MUA doesn't really have to know or care. You can implement lockout (with appropriate UI to prevent mistakes) by simply triggering on AutoCrypt headers where the From: address is an e-mail address you (you the MUA) recognize. This will be very little additional code and may actually derive very naturally from the state syncing code already being proposed. This is both more robust and less work than the whole IMAP thing.

**Comment by dkg** [comment]
@Valodim: RFC 6154 is optional, and there are definitely MUAs that don't respect it.  Furthermore, i ultimately hope that the SMA is abstracted beyond IMAP, where RFC 6154 isn't relevant.  (i want this to work with MAPI, EWS, etc)

**Comment by dkg** [comment]
@BjarniRunar: i regularly receive spam mail that claims to be `From:` my e-mail account.  That e-mail has no Autocrypt header in it.  What should my MUA do in that case?

**Comment by BjarniRunar** [comment]
@dkg: Nothing. You don't need to even consider acting locked out unless you see an AutoCrypt header. But this is a case which may need special consideration in the state management logic.

**Comment by dkg** [comment]
And as @Valodim pointed out on IRC, if we want level 0 clients to back off when level 1 clients are active, we need a well-defined way that level 1 clients can robustly lock out level 0 clients.

**Comment by BjarniRunar** [comment]
@dkg: I think this isn't a good venue for fleshing out implementation details like that. But I don't see anything in the scan-headers-for-AutoCrypt-lockout-triggers that prevents us from speccing it in such a way that level1 can lock out level0. This is just a few bits of information, if we can put it in IMAP, I'm pretty sure we can also put it in the header.

**Comment by dkg** [comment]
@BjarniRunar: what about spam that contains an arbitrary `Autocrypt:` header?  what state management logic are you proposing?

Losing the explicit lockout mechanism would be a loss in functionality for the overall ecosystem, and it doesn't seem like significant additional complexity to me.

**Comment by dkg** [comment]
@Valodim: your question about implementation complexity and where the identity-creation/handling is done is well-taken.  I think a simpler way to approach this is to have the identity creation have multiple states.  there's `none`: "existing account, no Autocrypt info",  `locked-out`:"existing account, somoene else controls Autocrypt", `provisional`: "existing account, provisional Autocrypt info", and `registered`:"existing account, registered Autocrypt info".

transitioning from `none` to `provisional` is all done locally -- that's the key generation stage.  In either `none` or `locked-out` or `provisional`, you never send `Autocrypt` headers.  When you have access to the SMA, if you're in `provisional`, you can move it to either `registered` or `locked-out` on the basis of what is in the SMA.

**Comment by BjarniRunar** [comment]
@dkg: Spam that contains arbitrary AutoCrypt headers breaks all sorts of other things too. We're not handling that for the encryption state management itself, I don't see why it's suddenly a blocker for this.

You've got two implementers telling you there is non-trivial complexity in IMAP-based strategies, as well as me pointing out common use-cases where the IMAP-based strategies cannot work and the other can... you're still not seeing it, but that doesn't invalidate the concerns. :-)

Remember simplicity and ease of implementation was an explicit goal for AutoCrypt in general and level0 in particular. Not needing to worry about IMAP at all for level0 is a *huge* simplification. But I think I've made my case, I'm going to shut up now and let others chime in.

**Comment by Valodim** [comment]
Not doin' lockout anymore :)
