### ISSUE TITLE
Add paragraph about secret key management to high level overview

### ISSUE THREAD

**Issue by Valodim** [autocrypt/autocrypt#221]
Right now, the high level overview section is missing a brief description of what we do (and don't do) for secret key management. This mostly involves the scanning and setup message mechanism, and roughly why we descoped imap.

**Comment by dkg** [comment]
I agree that this would be good to have.

@Valodim, do you have a PR to propose for this?

**Comment by Valodim** [comment]
I'll try. But I'm working on an entirely project this week so I'm not sure if I'll really find the time and mindset to do it.

**Comment by hpk42** [comment]
The PR #229 adds a little info on secret sharing to the introdocution paragraphs which maybe should be a "0. background" section?

**Comment by dkg** [comment]
Making the introduction "section 0" is beyond my latex skillz, though i wouldn't object if someone wanted to do it.

I think the changes in #229 are distinct from what @Valodim is suggesting is needed here.  the Overview section is intended to be more technical than the Introduction.  As i commented in #229, i don't think the overview should talk about "secret key sharing", but should talk about the "multi-device" use case instead.

**Comment by hpk42** [comment]
@dkg the current state of #229 does not talk about secret keys anymore but multi-device.

**Comment by dkg** [comment]
This ticket asks for edits to the high level overview. #229 was about fixing the introduction/preamble.  so i don't think this is resolved yet.
