### ISSUE TITLE
drop or fix content of linked ":doc:"s ...

### ISSUE THREAD

**Issue by hpk42** [autocrypt/autocrypt#225]
level1.rst contains a number of ``:doc:`` references that are not part of the spec and will not be readable/clickable from the PDF.   For each link i suggest:

- to drop them if they are not really neccessary to understanding level 1 ... or 

- to try incorporate them directly in the spec (e.g. canonicalized e-mail address) 

- if they remain, then make sure at least the directly linked doc has comparable quality
  to the spec

**Comment by Valodim** [comment]
Yes! I very much agree with this, and it should be part of the level 1 freeze. It's very important to have a self-contained spec (whether it's pdf or something else)

**Comment by dkg** [comment]
I agree with this as well.  more to do…

**Comment by dkg** [comment]
So i see five external `:doc:` references remaining:

 * in the introduction, where it calls out to `next-steps`
     I don't mind leaving this one in (though i'm not sure it should talk specifically about "Level 2", but maybe should talk about "future revisions").
 * two references to `address-canonicalization`
     This should probably be incorporated explicitly, or else we should drop the idea that Autocrypt clients all do the same address canonicalization.  I think if we want predictability, we should encourage address canonicalization, though.
 * `optional-state`
     This is now out of date given the overhaul to the `peers` table, but it's could be brought back into shape.  I'm reluctant to cut out all references to it from the spec because i want to honor the work that @BjarniRunar put into it, and to encourage more experimentation like this.  I'm not sure how to resolve this one.  Can we designate a URL within https://autocrypt.org/ as a location for this kind of experimentation and forward-looking proposals that aren't yet merged into the main spec?
 * `other-crypto-interop`
     This will (hopefully) be killed by either #224 or #227
 * `bad-import`
     This is concretely useful information about a specific failure mode of a common implementation.  Maybe it also deserves a permanent home somewhere that we can point to as an external URL in the spec?

It might be useful to open a separate issue for each one of these remaining concerns.

**Comment by dkg** [comment]
OK, we have 3 left, and i've opened separate tickets for each of them, along with  my general suggestions for what should be done:

- [ ] #237 
- [ ] #238 
- [ ] #239

**Comment by hpk42** [comment]
There now only is #238 left for removing the last occurence of ``:doc:`` (optional-state).  Close this issue in favor of #238.
