### ISSUE TITLE
change from "The MUA SHOULD NOT protect the secret key with a password." to UX

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#233]
We don't actually care about whether the key is protected with a password.  we care about whether the user has to enter the password to read or send mail.

If the key is protected with a password that is unlocked upon session login, or upon "opening my mail app", i don't think that would be objectionable.

So this requirement should be phrased in terms of UX specifically -- what kind of interaction should be required (or forbidden) and when?  but not in terms of "is a password used".  The sentence before the objectionable one is actually pretty good:

> The secret key material should be protected from access by other applications or co-tenants of the device
> at least as well as the passwords the MUA retains for the user’s IMAP or SMTP accounts.

**Comment by hpk42** [comment]
+1 if it maintains the strictness of "SHOULD NOT" for avoiding per-message passphrase entry.
