### ISSUE TITLE
Maintain knowledge about time of original receipt when sending out gossip keys

### ISSUE THREAD

**Issue by hpk42** [autocrypt/autocrypt#236]
Raised by George Danezis who reviewed the Nov7th version of our 1.0.0rc1 spec:

> In 2.6 Key gossip: there is a general issue with key gossip. The
> sender of the gossip header does not specify how recent or stale the
> gossip information is, and the recipient MUA uses the messages
> receiption data as a proxy for this. This means that when I send my
> yearly Holliday greetings card to family, that I contact once a year,
> I may be propagating stae keys to all my  contacts. Is that an issue? 
> Should the gossip only include "recent" keys? Should it include a 
> timestamp of how recent the info is? (At the expense of contact privacy though).

I agree with the concern.  How about we introduce a "seenfirst_timestamp" which is the time someone got a mail of a key that is send further as a gossip key?  Gossiping a Gossip key further can then maintain that timestamp.  If we gossip gossip keys, contact privacy is less of an issue. we could say that the timestamp should only maintain a time granularity of one week or so to reduce risks oif contact privacy leakage.

**Comment by Valodim** [comment]
The main goal of gossip is to always be able to "reply all", and gossip keys are only sent inside encrypted messages. So if the key used for some recipient is stale, then the first message will have been unreadable to them as well. The entire thread will remain unreadable, but this situation will remedy itself once the affected person replies (to all), propagating their new autocrypt key.

A related issue is that if we receive a gossip key that differs from one we received directly from the person. In that case, one of them will likely be wrong. We considered this before and couldn't come up with a good answer, so we said we'd leave it as is for level 1, iirc.

**Comment by dkg** [comment]
I thnk we're talking about Alice sending mail to Bob and Carol, with both Bob and Carol's keys in the gossip header.  I'll write below from Bob's perspective -- learning about what Alice thinks of Carol's key. 

If Alice is willing to mail Carol using this key, right now, then at some level Bob understands that Alice believes this key is "correct right now".  That's all that Bob should learn about Alice's internal state from this transaction (which he's already learned).

I don't understand the advantage of introducing a "seenfirst_timestamp" as proposed by @hpk42 above.  I don't see how it folds into any decision-making algorithm, and i don't see how Bob would adjudicate between two different `seenfirst_timestamp` values (e.g. if he receives a message from David to him and Carol).

Keep it simple.  If we get into transitive disclosures of date of key visibility, we're into a tangle that we don't want to get into, certainly for level 1.

If someone wants to flesh out a complete proposal (not just what to transmit and what to store, but how to concretely make use of what we've received and stored), and outline a particular scenario that we think is broken without that change, i'd be willing to consider it for something after level 1.

**Comment by hpk42** [comment]
Bob prefers the gossip key for Carol (received from Alice) if Bob's ``peer_state["carol"].public_key`` was obtained through receiving a mail from Carol say 40 days ago.  If Alice had a stale key (i.e. one from Carol' more than 40 days ago), not only Alice but now also Bob will use the stale key.  Carol will not be able to read mails from either Alice and Bob.   It's true that Carol can mail "i can't read this" which fixes the situation but given larger enough recipient groups i think the algorithm is very questionable.

By contrast, if we keep an ``origin_timestamp`` as an attribute to the Gossip header which indicates when ``keydata`` was already directly received from a peer, we have enough precision to quickly heal and converge on keys.  As soon as Bob mails back to Alice, both Bob and Alice will have a more recent key of Carol and Carol will be able read Bob's mail (and possibly the original mail if it is quoted).

**Comment by dkg** [comment]
I think i understand the rationale, but this opens up a large can of worms around transitive trust that we haven't had to deal with at all in the spec thus far. What do i set for `origin_timestamp` if i'm gossiping a key i've never heard about directly from the peer in question (that is, when i'm gossiping a key i've only ever received by gossip)?  I'd rather not open that can of worms.

#212 makes a suggestion for dealing with the choice of keys in the "reply" case as a special case specifically, which might be a better way to solve this problem.  But i think it should be left to after level 1.

**Comment by dkg** [comment]
Setting aside the issue of timestamp granularity, are we willing to accept that a user's Autocrypt MUA will leak the information "I have received mail directly from recipient X in the past" to all recipients?  Gossip as currently formulated does not do this, because it's possible to be gossiping keys previously seen only from gossip, and there is no distinction between that and directly-received keys.

**Comment by hpk42** [comment]
Not sure we can easily ignore the issue.  Isn't it even possible with the current spec that Alice sends a mail to Bob and Carol and encrypts it by using a recently gossiped key for Carol, but then gossips a different key for Carol (which she directly received a 100 days ago)?  It seems odd that Alice can encrypt to a different key than the one she gossips.

**Comment by dkg** [comment]
Where does the spec suggest that you can or should gossip a different key than the one you encrypt to?  we should make it explicitly clear that message senders SHOULD send the same keys as gossip headers that they encrypt to.

**Comment by Valodim** [comment]
We should, and that's part of the PR now. But only as a clarification; I'm not sure under what circumstances different keys would ever be sent in gossip headers than used for encryption

**Comment by r11r** [comment]
Hi guys, I'm new to the project and I know that you're busy with finalizing Level 1. But I'm following autocrypt with high interest and wanted to share my thoughts on potentially stale gossiped keys:

Would it be possible to store and use multible keys per contact? Say Alice recived a mail from Bob a month ago containing key B1. Now in a mail from Carol to Alice and Bob, there is a gossip key B2 for Bob.

To minimize the amount of unreadable emails, Alice could store both keys (maybe even with an additional note, that B2 came from Carol) and encrypt all further messages to Bob with both keys (and maybe also gossip both keys in multi-recipient messages. As soon as Alice gets a direct message from Bob, she knows what his most recent key is and can delete all other keys from her storage.

In an advanced case, if Alice also stored the information that key B2 was gossiped by Carol and Carol gossips key B1 for Bob in a later message, Alice could also delete key B2 from her storage, following the assumption of Carol, that key B1 is prefered to use (whereever Carol got this information from).

While i know that this would increase overhead in emails, it would decrease the chance of Bob being not able to read Alices messages without adding any timestamp to the gossip-key field.

A totally different way of judging would be to use the key with the most recent creation date, but this again would require knowledge of the OpenGPG standart, as being the problem in #242.

**Comment by Valodim** [comment]
Actually, we do store both keys now with their last seen timestamps, and decide at send time which one to use. This was changed rather late and apparently we forgot about this issue when we did :)

**Comment by dkg** [comment]
We store both keys and remember their last-seen timestamps.  but this ticket appears to be about trying to emit the timestamps that we see them in gossip headers as well, and we are currently *not* doing that (and i hope we will not start, because i don't believe that the privacy costs are worth whatever meager benefits we might get)

**Comment by Valodim** [comment]
This ticket is fairly confusing at this point because the spec changed in the meantime, up to Autocrypt 1.0. If someone wants to bring this up again, please make a new ticket working from the current spec.
