### ISSUE TITLE
move `doc/bad-import.rst` to somewhere else, reference from spec

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#239]
`doc/bad-import.rst` is concretely useful information about a specific failure mode of a common implementation (GnuPG).  It's also somewhat out of date.

It deserves a permanent home somewhere, and we should point it as an external URL in the `level1` spec.

Since it's GnuPG-specific, i think the permanent home should be GnuPG-specific too.  What about using https://dev.gnupg.org/T3277 ?

Blocks: #225

**Comment by hpk42** [comment]
i think it's fine to substitute the ``:doc:bad-import`` with the link to https://dev.gnupg.org/T3277 now and close this issue and remove the bad-import file.
