### ISSUE TITLE
require MUAs to check for OpenPGP expiration?

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#242]
We currently tell MUAs how to behave if they happen to know that some OpenPGP key is expired.
We do not tell them that they SHOULD verify that the key and subkey are not both expired.

I'd like to say that MUAs SHOULD perform this check.  It makes it much easier to implement a sensible key rotation schedule in the future if you can be sure that your peers won't encrypt to expired keys.

**Comment by hpk42** [comment]
Wouldn't this require peers to understand "Expiry" packets? (currently we don't IISIC)

**Comment by dkg** [comment]
a key's expiration timestamp is stored in subpackets in the OpenPGP signature packet.  We do indicate that peers should have some concept of the OpenPGP signature packet.

Note that i'm talking about expiration, not revocation.

**Comment by Valodim** [comment]
So far, clients need to have no concept of openpgp keys at all, other than "save as opaque blobs, and hand to openpgp engine for encryption if autocrypt recommendation so indicates". Unless you absolutely think we can't live without this I'd prefer we left this out of level 1.

Maybe we should open an "honorable mentions" page (or amend next-steps) or something, these last minute changes are really piling up :\

**Comment by dkg** [comment]
I'm fine with leaving it out of level 1.

**Comment by azul** [comment]
We currently say:
>For the purposes of the rest of this recommendation, if either public_key or gossip_key is revoked, expired, or otherwise known to be unusable for encryption, then treat that key as though it were null (not present).

So we have some notion of expiry. We just don't specify if it's a requirement or not. Is that what this issue is about?

**Comment by dkg** [comment]
I think the language has gotten tighter than it used to be -- it used to be something loose like "if you happen to notice that the cert is revoked or expired, then..."

But we're definitely not asking folks to pull in revocation checks (i hope!) -- are we asking them to calculate expiration?  if it's a MUST, then we should be more specific about it (do we care about subkey expiration vs. primary key revocation, etc?)

Again, i don't think this is L1, but we should include explicit guidance for the future.

**Comment by hpk42** [comment]
i think the sentence is there to accomodate/integrate with those e-mail muas which already do some form of key validity verification.  Everyone here agrees that there is no need to further discuss or refine the sentence for L1.
