### ISSUE TITLE
Finalize website design and put it online, strike readthedocs

### ISSUE THREAD

**Issue by hpk42** [autocrypt/autocrypt#249]
there is a new user-facing website under construction, https://autocrypt.org/en/website

The designer is about to finalize the logo design (we take the u-lock) and suggest refinements to the user-facing website layout.  @dignifiedquire and me are going to put this into proper css and do a PR. 

we also need to make effective @azul's work on removing "readthedocs.org" in favor of directly serving from autocrypt.org.  It's already generating a PDF and puts it to autocrypt.org but nginx does not point to it yet.

**Comment by hpk42** [comment]
- the new CSS and final images are integrated with the website now. 
- PDF are auto-generated and can be downloaded
- readthedocs is not used anymore, we serve things directly

what is missing: looking/streamlining the entry point page's texts and maybe also the links on the navigation bar.

**Comment by lefherz** [comment]
I removed the "News" Entry from the side menu - the .rst is still in the repo, but as it neither appears there nor in https://autocrypt.org/en/website/contents.html it is hidden well enough, I think.

**Comment by dkg** [comment]
What else needs to be done to wrap this up and publish?

do we need reviews?  textual changes? design improvements?  infrastructure improvements?

**Comment by lefherz** [comment]
We definitely need textual changes, the "Our mission" text has rating D on https://readable.io/text/ . If no one objects, I would try to optimize the text so it fits their simplicistic guidelines for readability. The target group for this text would be users.

Also, https://autocrypt.org/en/website/ doesn't seem to show the current version of https://github.com/autocrypt/autocrypt/blob/website/doc/_templates/globaltoc.html , I thought I removed the "News" part from the table of contents.

It would also be good if someone rechecked https://autocrypt.org/en/website/install.html to see if it reflects the current state of things.

**Comment by lefherz** [comment]
I'm also having a website design workshop tomorrow at ownCloud, I plan to review the current autocrypt.org after I'm a bit smarter ;)

**Comment by hpk42** [comment]
i think we can close this issue. there are things to be improved still but it does not need to hold up 1.0 releasing.

**Comment by lefherz** [comment]
Doesn't this only mean we should remove the milestone, but let the issue open?

Because before things are "finalized", it should at least be checked why the "News" item is still on the toc, and also pushed to the master tree.

So I suggest we remove the milestone, but reopen the issue, as it is still a to do, but not a time-critical.

To have more discussion about how the website should look like and to finish the layout, I'd suggest to have another session on 34c3 - then we have the right environment to be creative and the right people around for the good ideas.

**Comment by dkg** [comment]
If there are specific concerns with the website, i'd be happy to see them opened as individual issues -- it's hard for me to tell how to close an ticket titled "finalize website" because i know websites are never final :)

**Comment by lefherz** [comment]
Yeah, there will be changes afterwards, of course :D but with "final" in this issue I think a pull request from website to master is meant.
