### ISSUE TITLE
discuss aliases 

### ISSUE THREAD

**Issue by hpk42** [autocrypt/autocrypt#25]
Out of a discussion with @Valodim today: In level0 docs we currently say that each account maintains separate Autocrypt state but we do not discuss or mention what happens with different aliases/identities within an account.  Do we want to generate a single key and re-use it for different aliases i might use for this account?  Or rather a fresh key for each alias/identity?

**Comment by azul** [comment]
I think its pretty clear for now that we only want one key per account even if there are multiple aliases. Multiple keys would increase the complexity of the Autocrypt Setup Message. It also poses significant syncronisation issues if new aliases are used on different devices and new keys get created.

One option seems to be to have a single key and add user ids to it for all aliases it is used for. When creating an autocrypt header the userids that differ from the identity used for that message will be stripped of.

If the accounts key has never been used for an alias the client may ask the user if they want to enable autocrypt for that identity. If they choose to the alias could be added to that keys userids.

It may make sense for users to not have autocrypt enabled for certain aliases. The prefer-encrypt=mutual choice might also differ for different aliases allowing for aliases for unencrypted communication when away from the keys (browser / mobile / holidays / whatever).
