### ISSUE TITLE
generate secret keys from fixed prng seed -> "Autocrypt number"

### ISSUE THREAD

**Issue by Valodim** [autocrypt/autocrypt#255]
late night #autocrypt chatter

> 01:48      Valodim> so actually, in an autocrypt context, if we can gain some traction on clients actually implementing a standard, then generating secret keys from a fixed random seed that we give to the user as a backup code would be quite feasible
> 01:49      Valodim> there are two major drawbacks: 1) requires deterministic CSPRNG accross platforms, 2) must be done at key generation time
> 01:50      Valodim> but if we have that, "This is your Autocrypt number. You can input it into any Autocrypt client to be able to read your secret mail on that" sounds like a pretty neat prospect
> 01:50          dkg> Valodim: not for level 1 please
> 01:50      Valodim> of course not

**Comment by dkg** [comment]
I dunno why it should be a number.  it could be your "autocrypt poem" instead :)

**Comment by hpk42** [comment]
Interesting.  If we had some kind of random seed/number to base secret key generation on, then different kinds of keys could be generated from it possibly, right?  For example, you could have a curve key and an rsa pgp key both based on that number, or maybe even a non-pgp key.

**Comment by Valodim** [comment]
closing stale issue
