### ISSUE TITLE
User IDs

### ISSUE THREAD

**Issue by Valodim** [autocrypt/autocrypt#26]
The two key phrases about user ids in the draft are currently this:
```
a user id that SHOULD be set to the e-mail address of the account
```
and this
```
The content of the user id packet is only decorative, and MAY contain different
values from the to attribute, or even the empty string.
```

This is fairly unrestrictive, so chosen because autocrypt itself isn't directly affected by the actual content very much. I think we should put at least slightly more thought into this because it affects verification, and if clients ever generate more than one key (related #25) it also brings up a bunch of questions.

**Comment by Valodim** [comment]
Related discussion result, where we considered none, hashed, or fixed-string user ids besides raw addresses: https://autocrypt.readthedocs.io/en/latest/faq.html#why-did-you-choose-the-raw-e-mail-address-for-the-user-id

**Comment by azul** [comment]
Turns out empty userids may not be a good idea for now: https://dev.gnupg.org/T3203
@Valodim and me also discussed user ids in relation to aliases. Will write down our findings in #25
