### ISSUE TITLE
website staging practice needs an overhaul

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#292]
we currently test/propose website development by proposing a branch `foo` and then it shows up at https://autocrypt.org/en/foo/

this is convenient for testing, but it means that sometimes someone outside the project sees such a URL and then links to it directly.  This has two problems:

 * something that is being proposed (maybe controversial) looks "official" to the outside world
 * those links aren't stable or well-maintained.  as soon as the branch is merged and removed, those links go away, leaving a dangling link.

We should change how we handle proposed changes to the website.  I think:

 * we should create https://staging.autocrypt.org/ or https://unofficial.autocrypt.org, which uses the scheme we currently use, to make it possible to deploy and view changes
 * the master branch (and the master branch only) should be rendered to https://autocrypt.org/ directly, rather than to https://autocrypt.org/en/latest/ -- no other branches should be rendered on the main website
 * everything rendered at https://staging.autocrypt.org/ should be visibly different (e.g. the background could say "draft", the favicon could be a warning symbol, a dismissable in-window popover could explain that this is a draft, etc)

**Comment by hpk42** [comment]
i agree that marking branches to be regenerated in a less official way makes sense.

**Comment by dkg** [comment]
fwiw, i'm happy to help with the deployment of this if it would be useful.  If you want to break it into smaller tickets and assign me a part, please do so.

**Comment by fschulze** [comment]
@dkg If you have an idea to make everything besides master visually different, then be my guest on that part. I think the favicon is too little, as Safari almost never shows it for example. I think this needs to be done on the Travis and/or Sphinx level.

**Comment by fschulze** [comment]
The master branch is now rendered on https://autocrypt.org, https://autocrypt.org/en/latest redirects to it. All other URLs like https://autocrypt.org/en/website now redirect to https://autocrypt.org/_unofficial_unreleased_docs/website/ (or equivalent).

**Comment by dkg** [comment]
This is great, @fschulze++ !!

@fschulze, it's not clear to me how you did this fix specifically -- what changed, how it changed, etc.  I'm pretty happy if you want to commit to doing this kind of work regularly, but if you want some backup, i'd be happy to see pointers to the relevant configuration changes so multiple people could maintain them.

So i think the things that remain on this ticket are:

 * switch from `/_unofficial_unreleased_docs/`  to a subdomain (maybe not particularly important, though same-origin policy might be worth considering).  I think @fschulze already set up `staging.autocrypt.org`, we just need to get and configure an X.509 certificate for it.  and then we need to move the non-master branches into only that virtualhost. 
 * visual distinctions for the non-master branch. i've just opened #295 about this.

**Comment by fschulze** [comment]
On the server the docs are hosted from, I made these nginx config changes:
```diff
diff --git a/nginx/sites-available/autocrypt b/nginx/sites-available/autocrypt
index 902a9ed..4ce5939 100644
--- a/nginx/sites-available/autocrypt
+++ b/nginx/sites-available/autocrypt
@@ -49,16 +49,16 @@ server {
 
     add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
 
-    location /en/latest {
-        alias /home/autocrypt/build/master;
-    }
+    rewrite ^/en/latest$ / redirect;
+    rewrite ^/en/latest/(.*)$ /$1 redirect;
+    rewrite ^/en/(.*)$ /_unofficial_unreleased_docs/$1 redirect;
 
-    location /en {
-        alias /home/autocrypt/build;
+    location /_unofficial_unreleased_docs {
+        alias /home/autocrypt/build/;
     }
 
     location / {
-        return 302 /en/latest;
+        alias /home/autocrypt/build/master/;
     }
 }
```

**Comment by dkg** [comment]
I've just set up the X.509 certs and the web service for https://staging.autocrypt.org/ -- branch `foo` will now be visible at https://staging.autocrypt.org/foo

So the only thing that remains on this ticket aside from #295 is to remove `https://autocrypt.org/_unofficial_unreleased_docs` , i think.

**Comment by dkg** [comment]
OK, i did the last switch with this:

```diff
diff --git a/nginx/sites-available/autocrypt b/nginx/sites-available/autocrypt
index 4ce5939..4bae1ad 100644
--- a/nginx/sites-available/autocrypt
+++ b/nginx/sites-available/autocrypt
@@ -51,7 +51,7 @@ server {
 
     rewrite ^/en/latest$ / redirect;
     rewrite ^/en/latest/(.*)$ /$1 redirect;
-    rewrite ^/en/(.*)$ /_unofficial_unreleased_docs/$1 redirect;
+    rewrite ^/en/(.*)$ https://staging.autocrypt.org/$1 redirect;
 
     location /_unofficial_unreleased_docs {
         alias /home/autocrypt/build/;
```
