### ISSUE TITLE
make non-master websites render differently

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#295]
When rendering the web site from a non-master branch, it should be visually distinct from the master branch -- see the discussion in #292 .

I'm going to try to do this with sphinx.

**Comment by fschulze** [comment]
This might help: https://docs.travis-ci.com/user/environment-variables#Default-Environment-Variables

You could check for ```TRAVIS_REPO_SLUG``` being ```autocrypt/autocrypt``` and ```TRAVIS_BRANCH``` being ```master```. Since conf.py is Python, it should be easy. You could change the logo or use another theme (derive from the normal one and change only one thing?).

**Comment by dkg** [comment]
I'd just as soon not use travis-specific things, and have it all done directly from sphinx, so that my local "make html" covers the same ground.

**Comment by dkg** [comment]
ok, that didn't appear to work.  i don't think i understand travis well enough to make this happen appropriately.  I've manually reverted the change in question and left it commented out in doc/conf.py in the hopes that someone else can figure this out.

**Comment by dkg** [comment]
I figured it out and it works now!  thanks to @fschulze for pointing me in the right direction.
