### ISSUE TITLE
consolidation: move MX handling of autocrypt to autocrypt.org VM

### ISSUE THREAD

**Issue by hpk42** [autocrypt/autocrypt#301]
Currently, there is a mail-handling VM which handles the "bot" alias. We also have a autocrypt.org VM where @dkg, @fschulze and me have accounts and sudo access, the /etc is vcs-controlled with etckeeper there.  It also runs an experimental mailman3 installation which is exposed as https://lists.codespeak.net -- with the idea being to add autocrypt/mailman integration in 2018.  The VM also has proper letsencrypt handling (for autocrypt.org) and this proper cert can be used for TLS/SMTP there. 

i think it makes sense to shift the bot@ and autocrypt/mx handling to the autocrypt.org VM and ask around if anyone else wants to help care for maintaining the MX and web facilities for autocrypt.org.

**Comment by dkg** [comment]
I could help with this postfix installation if that would be useful, though i'd want to plan it out a bit.

as a first pass, i'd set it up with both inbound and outbound opportunistic TLS.

Then there's a question of whether we want DKIM-signing, SPF records, or DMARC as well.

For the bot at least (probably other aliases too), we also probably need to discuss spam mitigation strategies.

Finally, we need to think about storage -- how much storage do we allow, do we have message destruction policies, etc?

**Comment by hpk42** [comment]
FYI the autocrypt.org (and lists.codespeak.net) website follows the https://github.com/fschulze/shared-admin/blob/master/docs/notes.rst setup, includes DKIM signing but not yet SPF and DMARC (needs to be added, for sure).  @fschulze is the main author of that effort and also helped with autocrypt.org infrastructure things.

**Comment by dkg** [comment]
ok, it looks like we've got postfix already installed and running on lists.codespeak.net, so we just need to make it accept mail for `autocrypt.org`, set up the proper aliases (e.g. for `press-team`), and set up the bot.  once that's all in place, we can re-point the A record for `mail.autocrypt.org`, and also update the local x.509 certificates for it.  (presumably we just want to add `mail.autocrypt.org` as a subjectAltName to the current cert for `lists.codespeak.net` -- is that correct?)

I'm happy to do the system-wide steps, but i don't know about setting up the bot.  @hpk42, looking at the current bot installation, i don't see how it works (though it does work, i tested it).  would you be up for handling the bot installation if i can get the other parts done?  are you ok with some level of bot downtime, if we can get the rest of the cutover to happen?

**Comment by gfa** [comment]
I'm happy to take this if @dkg agrees, also I'll need more info about the bot

**Comment by hpk42** [comment]
The bot runs from the former py-autocrypt, now https://github.com/hpk42/muacrypt package and in particular the "bot-reply" subcommand.  In ``/etc/postfix/master.cf`` there currently is this line:
``botreply unix -    n    n    -    1    pipe flags=R user=bot argv=/home/bot/venv/bin/autocrypt bot-reply --fallback-delivto=$recipient --smtp=localhost,25``

This pipes the mail to ``muacrypt bot-reply`` which in turns sends a reply-mail.  You can mail it right now at ``bot@autocrypt.org`` FWIW. 

i think the current ``muacrypt==0.8.0.dev4`` (installable via ``pip install --pre muacrypt``) should work fine already for ``bot-reply`` purposes.

**Comment by fschulze** [comment]
@hpk42 I assume that is on the current server? Because I can't see that entry on the lists.codespeak.net server.

**Comment by hpk42** [comment]
@fschulze yes, it's on ``mail.autocrypt.org`` a different VM that we want to merge with ``autocrypt.org`` and then get rid off.  One VM less to care/consider for.

**Comment by dkg** [comment]
@gfa i'm happy to have you take this on if you want.  I'd offered to do some of it but clearly haven't gotten to it, and you've managed to raise more information on this thread than i had :)

let me know if you want help! :)

**Comment by gfa** [comment]
I've completed the setup for a test account, bot@localhost.codespeak.net, but I think it would be better to move the old bot config, so the keys are the same (otherwise ppl with autocrypt capable MUAs will see broken emails)

then there is the MX record, but first things first

**Comment by gfa** [comment]
@hpk42 ^^

**Comment by hpk42** [comment]
On Sat, Jan 13, 2018 at 03:34 +0000, gustavo panizzo wrote:
> I've completed the setup for a test account, bot@localhost.codespeak.net, but I think it would be better to move the old bot config, so the keys are the same (otherwise ppl with autocrypt capable MUAs will see broken emails)

sounds good!

i don't think it's nececssary to keep the keys. We can just regenerate
and use new ones.  also there i no need to keep history.

> then there is the MX record, but first things first

that indeed seems to be the remaining thing now. Let me know
when you want to do it --> maybe co-ordinate on IRC?

holger

**Comment by gfa** [comment]
Hi

The bot is ready :)
Just point the MX to the server

-- 
Sent from my mobile. Please excuse my brevity and typos.

**Comment by hpk42** [comment]
will try to do that tomorrow. 

We also need to transfer the press-team alias.
i put the original / current aliases 
under /home/hpk/mail-autocrypt-aliases

if you get to transfer them to the setup you already did
that'd be nice.

holger

**Comment by hpk42** [comment]
Thanks @gfa -- justed tested and the bot replies correctly from the new IP address!
I think we can now disable/deactivate the old VM that served mail.autocrypt.org, right? 

@varac originally set this up and i can mail him accordingly.

**Comment by dkg** [comment]
What else needs to be done here?  can we close this issue?

**Comment by gfa** [comment]
good catch dkg, nothing else needs to be done here. closing
