### ISSUE TITLE
add press-team@autocrypt.org alias

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#308]
[i proposed a press team on the mailing list](https://lists.mayfirst.org/pipermail/autocrypt/2017-December/000289.html).

Could we set that up?  maybe we should also point `contact@` to the same list just in case someone is trying to write to it..

I know that #301 needs to be worked on --  i'm happy to work on it, and will transfer the alias when that happens.  but i hope this change doesn't need to block on #301.

**Comment by dkg** [comment]
assigning to @hpk42 because i don't know who else has permissions to edit `/etc/aliases` on the current MX.

**Comment by hpk42** [comment]
see my suggestion #312

**Comment by hpk42** [comment]
the press-team at autocrypt.org is configured now with the members mentioned in the press-team doc.
