### ISSUE TITLE
RFC needed

### ISSUE THREAD

**Issue by dumblob** [autocrypt/autocrypt#310]
I just stumbled upon this effort and I like the idea of the opportunistic encryption and the user friendliness.

My question is, whether you're planning to submit an RFC for this? Without that it'll be very difficult in my opinion to get it spreaded (I'm talking mainly about Google web MUA, Microsoft web MUA and Outlook Windows binary, and a few other well-known MUAs).

I could not find any word anywhere about submitting an RFC. Any pointers?

**Comment by Valodim** [comment]
We might work this into an RFC at a later point, but so far this is not on our roadmap. We have some people in our group that actively work on IETF standards as well, and from this experience made the informed decision that at least for now, IESG workflows wouldn't leave us as flexible as we want to be.
