### ISSUE TITLE
Please support autocrypt and traditional PGP simultaniously in Enigmail

### ISSUE THREAD

**Issue by zvyn** [autocrypt/autocrypt#314]
This report is based on my experience in testing the enigmail nightly at 34C3.

Scenario:
3 Users: Expert A (e.g. software dev), Expert B (e.g. sysadmin), Novice C (e.g. the client)

The experts have PGP set up the traditional way and care a lot about signatures and validity (e.g. signing software releases or encrypted passwords) and will always check key validity for _some_ peers over another channel.

The novice has autocrypt set up and encrypts emails with peers who did the same.

As I see it a hard autocrypt on/off switch would prevent the novice from getting the public keys from the experts, therefor communicating in plain text with them.

I would propose to have a "mixed" mode for experts where public keys are exchanged in autocrypt style while leaving the checks of the classic enigmail set-up in place. (As opposed to keeping the two worlds completely separate).

This would also benefit the experts who only care about validity / signatures for some users and would happily default to an autocrypt set-up for others (e.g. users not sending them configuration files or software patches).

**Comment by hpk42** [comment]
Copying in @pbrunschwig who maintains enigmail. Not sure if there already is an issue with enigmail but i guess it belongs there.

**Comment by pbrunschwig** [comment]
The idea that there is a distinction between Autocrypt keys and "regular" keys in Enigmail is wrong - the two worlds are _not_ completely separate. Keys from Autocrypt are imported in the GnuPG keyring just like any other keys. But this happens only in the moment when an Autocrypt key is needed for the 1st time. 

That is, if you decide that you only use trusted keys in Enigmail, then the Autocrypt keys will be imported in the keyring, but you still need to manually verify it before you can use it.

I think up to this point, that's in line with the Level 1 specification. But a "true" mixed concept where Autocrypt keys are only imported manually would be a different story. I currently won't do that.
