### ISSUE TITLE
34c4 workshop | Header missing when using Enigmail with Thunderbird Windows Client

### ISSUE THREAD

**Issue by ElenaPopa** [autocrypt/autocrypt#315]
**System config:**
Windows 10 Pro
Thunderbird 52.5.2 (32-bit)
Enigmail nightly build: build date: 2017-12-28, version: 2.0a1pre, git rev: a9eb85d7d7e9c88297ab3e7c949020db1ab6a015
Test user: viola@librechat.net/foobar (if of any help)

**Steps**
1. Configured Enigmail as per https://autocrypt.org/install-autocrypt-enigmail.html (Last update: Dec 6th 2017) with a small difference: to enable the config I went to Options / Options / Advanced / Config Editor
2. Followed though Enigmail Beginners Wizard for setting up a key 
3. Sent an email

**Issue:**
There was no encryption header. > https://www.screencast.com/t/C29sW9vIZgvG

**Enigmail log**
[enigmaillog.txt](https://github.com/autocrypt/autocrypt/files/1591466/enigmaillog.txt)

Other things tried:
1. Restart Thunderbird
2. Removed thunderbird user profile, recreated and went through the setup again
3. Inline PGP

**Comment by azul** [comment]
I submitted this to the enigmail bugtracker here: https://sourceforge.net/p/enigmail/bugs/728/

**Comment by hpk42** [comment]
Thanks for reporting @ElenaPopa ! i guess with the reference to the enigmail bug tracker we can close this issue, otherwise reopen please.
