### ISSUE TITLE
Send only Agent

### ISSUE THREAD

**Issue by tacruc** [autocrypt/autocrypt#318]
Is there a standart how send only agents, should behave?
This could be scripts on a raspberry pi or programms able to send but not to recive emails.

Can they just add their public key to the header and use the user public key if provided on a diffent way?
Would this behavior create any trouble?

**Comment by hpk42** [comment]
if an agent only ever sends mail then why would it add an autocrypt header? That would only be useful if the agent could receive mail.

**Comment by dkg** [comment]
@hpk42 maybe they can send but they know there are other co-agents which can receive, and they want to share autocrypt policy with those co-agents.

If that's the case, i don't think there would be a problem with such an agent being manually configured with the correct outbound header.  but this is *very* far from the standard user's e-mail practice, so i'm not sure how much we should contort the specification to account for it.

**Comment by tacruc** [comment]
So my usecase is that I have a Webservice. It is nextcloud and I would like to use the header to autodeploy the public key of the server to the users. There user have the ability to upload their public key in the Webinterface.

Am 4. Januar 2018 05:57:36 GMT+05:30 schrieb dkg <notifications@github.com>:
>

**Comment by dkg** [comment]
@tacruc what kind of guidance would you be looking for to make such an implementation?

If you've already built your implementation, maybe you'd be up for proposing a paragraph of text describing what you did, or any unusual decisions you found yourself forced to make?

**Comment by Valodim** [comment]
closing stale issue
