### ISSUE TITLE
guidance what to do when detecting multi key situation

### ISSUE THREAD

**Issue by azul** [autocrypt/autocrypt#319]
We have specified the autocrypt setup message and hope that clients will figure out that autocrypt has already been used with an account. However I think most clients have not implemented this precaution and even if they do they might still end up in a scenario with different keys on different devices because the user deleted the ASM, ignored a warning or so.

How will this show up in the client:
* unreadable mail
* different autocrypt headers in outgoing mail

What should the client do in this scenario? Here's a simple proposal:
* warn user about two keys being detected.
* propose to send an ASM to the other client so the keys can be synced

On retrieval of an ASM with a key already setup:
* keep the old secret key (in case more mails encrypted to it arrive)
* start using the new key from the ASM
* sign the new key from the ASM with the old key to indicate the change was on purpose

The last step would allow peer clients to not indicate a key loss as the signature indicates this was a proper transition.

edit: #277 deals with what to do when receiving an ASM on a device where autocrypt is already setup.
The minimal level 1 solution outlined in #300 requires the user to choose one key over the other and loose the ability to decrypt mails encrypted to the other key.

**Comment by hpk42** [comment]
signing would extend the key format that is specified with Level 1, wouldn't it? 
I think it's fine to just use the ASM-transfered new key -- Autocrypt is opportunistic anyway and users may regenerate their autocrypt key at any time.

**Comment by dkg** [comment]
isn't this the same question as #277?

**Comment by azul** [comment]
@dkg thanks for the pointer. I think #277 is for the second part... what to do if another setup message shows up. I was more thinking about what to do if:
* mails in the outbox have a different autocrypt key
* unreadable mail comes in
* something else indicates the user is trying to use different keys for the same email address

I'm not entirely sure if it makes sense to separate the two. Will make sure to read up on #277 first.

**Comment by azul** [comment]
@dkg Sorry for dumping this issue in here before first searching for past discussions. Looks like #294 also deals with the situation.

**Comment by azul** [comment]
Renamed the issue and edited the description to narrow down the scope. Now this issue should explore what a client can do when detecting a multi key situation. #277 is about what to do when seeing another ASM.
