### ISSUE TITLE
License

### ISSUE THREAD

**Issue by juga0** [autocrypt/autocrypt#32]
License seems to be missing for doc and code.

**Comment by juga0** [comment]
In commit https://github.com/autocrypt/autocrypt/commit/4ce2d11936a03e313b40665b963cd53ef3a557ed: s/partly fixes #31/partly fixes #32

**Comment by Valodim** [comment]
The spec itself isn't software, so a software license seems odd. "This document is hereby placed in the public domain." seems to be a common and simple way to deal with this.

**Comment by juga0** [comment]
> partly fixes #32

I meant that this ticket was partly solved cause a license for the code was added (https://github.com/autocrypt/autocrypt/commit/4ce2d11936a03e313b40665b963cd53ef3a557ed) but not for the specs, and the title was:

> License seems to be missing for doc and code.

The license for the specs was not added because, iirc, there was not enough quorum/consensus in IRC.

There are licenses specific for documentation [0], "Public domain" is just a type of license [1], if i'm not mistaken.

[0] https://choosealicense.com/non-software/#data-media-etc, https://www.gnu.org/licenses/license-list.html#DocumentationLicenses, 
https://en.wikipedia.org/wiki/GNU_Free_Documentation_License#Other_free_content_licenses
[1] https://en.wikipedia.org/wiki/Public_domain

**Comment by juga0** [comment]
#188 closes this.
