### ISSUE TITLE
remove autocrypt impl repositories from organization 

### ISSUE THREAD

**Issue by hpk42** [autocrypt/autocrypt#320]
while discussing https://github.com/autocrypt/py-autocrypt/pull/19 on IRC @azul brought up that maybe py-autocrypt could be better moved out of the org.  I tend to agree and suggest that we strive to generally have implementations repos move out of autocrypt and rather have autocrypt.org point to implementations which then live elsewhere.  Small scripts to generate test data and probably also ui-usability tests are fine to remain though.  

autocrypt is really about the spec and the group overall is not really prepared to collectively maintain software.

**Comment by dkg** [comment]
It's fine by me if we want to move the implementations out of the organization.  certainly there's no one implementation that has all autocrypt contributors active in it.

**Comment by dkg** [comment]
what else needs to be done to complete this?  should we delete the older "inbome" or other repositories that are basically legacy now?

**Comment by azul** [comment]
To me deleting legacy repos or at least archiving them would make a lot of sense.
