### ISSUE TITLE
Team, projects and goals

### ISSUE THREAD

**Issue by juga0** [autocrypt/autocrypt#325]
From https://github.com/autocrypt/autocrypt/blob/master/doc/press-team.rst#current-team-members it not clear to me whether that's the press-team, the Autocrypt team or both.

I think it might be also useful to clarify to which projects are the contacts related to. If not there, probably then (or also) in https://github.com/autocrypt/autocrypt/blob/master/doc/contact.rst#L29

Another related issue is which is the roadmap of the projects involved. I think it'd be useful to understand (at least for an "independent contributor" point of view) which are the priorities for Panoramix, NEXTLEAP, etc, maybe it could be clarified in a Roadmap? (#324, autocrypt/py-autocrypt#20)

**Comment by hpk42** [comment]
did #326 which clarifies that the press-team doc is only about press-team members. 

IMO the press-team does not need to carry project affiliations. It's entirely possible (and likely as the autocrypt grows) that people are active and helping who are not directly associated with an implementation project.  I welcome that very much -- folks dealing with infrastructure, docs, user support/testing, trainers, providers etc. 

As to contact and dev-status pages i think we have some redundancy there wrt to project links.  Not sure how to merge and describe those -- dev-status shows as "implementations" in the navigation right under "specification" and should probably stay focused.  Maybe we could do a new ``related projects`` page where nextleap and panoramix and others can be mentioned, and maybe also alternative/complementary approaches like pep, wkd, vvv .... I suggest to keep this simple and not require roadmaps and detailed explanations as it's hard for anyone to get started on that page.  Let's take this better iteratively. 

summary: my tentative suggestion is to take out the projects links from contact.rst and rather point to "implementations" and "related projects"  pages (the latter also a new navigation item), with the latter having possibly paragraphs on how the projects are related.
