### ISSUE TITLE
add favicon.ico

### ISSUE THREAD

**Issue by hpk42** [autocrypt/autocrypt#329]
Can anyone help with creating a ``favicon.ico`` we can place on the web page? 
the original files are in ``doc/img/autocrypt*_orig.png``.  I guess it just needs to contain the u-lock.

**Comment by gfa** [comment]
PR comming

**Comment by hpk42** [comment]
the #336 PR needs to be adapted because it doesn't show up as https://autocrypt.org/favicon.ico 
i think ``make favicon.ico`` should create the file but it should be committed and be added to ``conf.py``'s ``html_favicon`` setting.

**Comment by gfa** [comment]
isn't http://autocrypt.org served from autocrypt.org (the machine)? i just check the docroot for autocrypt.org and the favicon.ico is not there.

**Comment by hpk42** [comment]
So favicon.ico is served now from https://autocrypt.org/favicon.ico -- good :)
however, it doesn't look nice yet on the browser tab.  it doesn't have transparent background. 
I wonder if it wouldn't better to try statically create a working "favicon.ico" file and just commit it, instead of regenerating it during build.  I briefly tried with gimp but failed to improve things.

**Comment by gfa** [comment]
Yes, it doesn't look good :( 
maybe the person that did the logo can provide a transparent version for us to convert in favicon.ico?

I generated at build time because it was just a few convert commands, not original work.  If we get a proper favicon.ico let's just save use it

**Comment by gfa** [comment]
I've converted aclogo.png to favicon.ico with better results, PR coming

**Comment by r10s** [comment]
@gfa: ahh, we did the same ... do not hesitate to throw my pr away, i'm fine with that :)

**Comment by r10s** [comment]
@gfa i've closed my PR and added a comment to yours (https://github.com/autocrypt/autocrypt/pull/338)

**Comment by r10s** [comment]
I tested gfa's pr locally and merged it; opened another pr to increase the favicon quality, #340

**Comment by gfa** [comment]
I've tested it locally, #340 looks a lot cleaner

**Comment by gfa** [comment]
#340 merged, closing
