### ISSUE TITLE
forwarding encrypted messages

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#342]
at some point, an autocrypt user will want to forward an encrypted message M (that they received from Alice) to Bob.

But Bob doesn't have keys to decrypt message M.  If the message is forwarded "inline" then it will most likely be decrypted during mesage composition, and then re-encrypted on message send.

but if it's forwarded "as an attachment" then it's possible that Bob will not be able to read the message.

Autocrypt should provide guidance for MUAs to decide what to do here.

**Comment by Valodim** [comment]
Any way to forward the original signature seems doomed to fail to me. The semantics are just too complicated to display - - With the possible exception of forward as attachment scenarios with reencryption, but that's so advanced I don't see it in autocrypt proper. 

Occam's razor: Treat it like any other plaintext message that would be forwarded. Possibly urge the user to not forward it unencrypted, akin to replies to encrypted mail.

**Comment by Valodim** [comment]
closing issue as stale
