### ISSUE TITLE
Add section numbering

### ISSUE THREAD

**Issue by Valodim** [autocrypt/autocrypt#345]
I noticed that we currently don't have a good way to reference sections, other than by title. We should enable section numbering for our document.

**Comment by dkg** [comment]
the sections in the pdf *are* numbered.  are you saying you want the same numbering to apply to the html?

**Comment by dkg** [comment]
something like the patch below adds section numbering, but they all start with 1 (because the document title is apparently read as a high-level section)

```
diff --git a/doc/level1.rst b/doc/level1.rst
index 2a1b651..6d56bea 100644
--- a/doc/level1.rst
+++ b/doc/level1.rst
@@ -48,6 +48,8 @@ both bugfix and backward-compatible feature releases.
 .. only:: builder_html
 
    .. contents::
+   .. sectnum::
+      :depth: 3
 
 .. only:: builder_readthedocs
 ```

**Comment by dkg** [comment]
see the "section-numbering" branch for a WIP attempt that i'm not satisfied with.

**Comment by dkg** [comment]
hm, [sphinx documentation](http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#sections) says pretty clearly that you should not use the `sectnum` directive.

**Comment by Valodim** [comment]
closing stale issue. we might want to revisit this at some point
