### ISSUE TITLE
Website: Change Setup Description for Enigmail

### ISSUE THREAD

**Issue by pbrunschwig** [autocrypt/autocrypt#346]
I completed the GUI for enabling Autocrypt:
1. Autocrypt is now enabled by default
2. enabling/disabling Autocrypt is now a per-account setting, available in the Account Manager

Therefore the last bullet on https://autocrypt.org/install-autocrypt-enigmail.html is now obsolete. If at all, you could write that enabling/diabling Autocrypt and the "prefer-encrypt" setting is now available via:
Windows, macOS: Tools > Account Manager > OpenPGP Security
Linux: Edit > Account Manager > OpenPGP Security

**Comment by azul** [comment]
@pbrunschwig yay! Thanks for turning it on by default :fireworks: :dancing_men:

**Comment by r10s** [comment]
great that Autocrypt is enabled by default :)
/me also celebrating \o/ /o/ \o/

**Comment by lefherz** [comment]
Merged :)
