### ISSUE TITLE
Can anyone participate in autocrypt?

### ISSUE THREAD

**Issue by juga0** [autocrypt/autocrypt#350]

**Comment by lefherz** [comment]
1. Anyone can join the IRC channel and join the discussion
2. some people are writing MUAs, and have "maintainer dictatorship" in their repositories, controlling participation themselves
3. Anyone can open a Pull Request to the spec or the website
4. to get part of the press team, the CoC team, or the github organization, you only have to ask, and get admitted, when you people trust you.

anything to add?

@juga0 is the goal of these issues to display this information on the website?

**Comment by hpk42** [comment]
sure although i guess it's only interesting for people who want to further or support privacy, end-to-end encrypted e-mail messenging in some way.

**Comment by juga0** [comment]
> @juga0 is the goal of these issues to display this information on the website?
@lefherz yes :) thanks for your answer, it could be added to the FAQ
