### ISSUE TITLE
Where are the contribution guidelines?

### ISSUE THREAD

**Issue by juga0** [autocrypt/autocrypt#351]

**Comment by lefherz** [comment]
Something like this should be in the README.md, I guess. 

For discussion on how you can even contribute, see #350 :)

**Comment by dkg** [comment]
I'm not sure which kinds of guidelines this is asking about. 

 * guidelines for how we expect contributors to behave are outlined in [the code of conduct](https://github.com/autocrypt/autocrypt/blob/master/CODE_OF_CONDUCT.rst) (also [on the website](https://autocrypt.org/code_of_conduct.html)
 * IPR coverage of  the main autocrypt repo (spec and website) are governed by CC0, as detailed in [LICENSE](https://github.com/autocrypt/autocrypt/blob/master/LICENSE)
 * mechanisms for contribution (mailing lists, meetings, IRC, etc) are [detailed on the website](https://autocrypt.org/contact.html).

are there other forms of contribution guidelines that you're looking for?

**Comment by lefherz** [comment]
Hm, I'm not sure if we really need this. The readthedocs link @juga0 posted is about guidelines which we don't need. We don't have a styleguide or something similar. I suggest to close this issue.

**Comment by Valodim** [comment]
Agreed. If someone wants to add something here, please reopen.
