### ISSUE TITLE
Is there any funding?

### ISSUE THREAD

**Issue by juga0** [autocrypt/autocrypt#353]

**Comment by dkg** [comment]
All work on Autocrypt at the moment is independently funded.  That means that individual implementers or contributors have been either self-funding, or have solicited external funds to cover their own work. I don't think that anyone involved with the project would object to any other outside funding, and we encourage funders to support Autocrypt-related efforts, especially those that feed back into the growing consensus around how to do encrypted e-mail in a sane and user-friendly way.

**Comment by juga0** [comment]
This answer could go in the FAQ :)

**Comment by dkg** [comment]
agreed!  want to submit a pull request? :)
