### ISSUE TITLE
Where/which is the "reference/example" autocrypt implementation?

### ISSUE THREAD

**Issue by juga0** [autocrypt/autocrypt#354]

**Comment by hpk42** [comment]
i don't think we have or need a reference implementation.  when i started py-autocrypt long ago i thought it might serve as one but now think it's better to just link to the various existing implementations like we do on the implementation page.   If we declare one implementation to be a "reference" it would need to receive a  scrutiny and agreement from others -- and currently everyone is busy enough with completing L1 support.  Time is better spent i guess on making interoperability tests and discussing open issues/wrong interpretations etc.

**Comment by dkg** [comment]
I also think that there isn't a single reference implementation, though we had talked about having a test suite that mail clients could import and report their resultant recommendations to check conformity.

For interoperable specifications, i think neutral test vectors are more likely to gain consensus from different implementers than claiming that "whatever `$reference_implementation` does is the Right Thing", which can be both demotivating, and wrong :)

**Comment by juga0** [comment]
i guess lines like this one still here: https://raw.githubusercontent.com/hpk42/muacrypt/3cc9a8843a5b8e73153d79ebdaf5db2d260e6d4c/doc/api.rst#L1 has made me confused in the past.

**Comment by dkg** [comment]
i'm going to close this ticket because while it might be relevant to docs in muacrypt or other projects, the autocrypt project doesn't have any stated reference implementation, and i think we'll keep it that way.
