### ISSUE TITLE
What is the goal of autocrypt?

### ISSUE THREAD

**Issue by juga0** [autocrypt/autocrypt#356]

**Comment by hpk42** [comment]
This is a very short issue report (as are some others you did recently) and i don't know what you are aiming at here.  Are you not sure yourself what autocrypt is about or have you heart from others that they are confused after reading the homepage? 

FWIW i think both the homepage and project background state quite a bit in the way of goals, approaches and there has been a lot of work and changes to make it easier for newcomers to understand what autocrypt is and what it is trying to achieve.  Not perfect, but also not all totally unclear i think.
