### ISSUE TITLE
Add autocryp.org email server to dnswl.org

### ISSUE THREAD

**Issue by gfa** [autocrypt/autocrypt#360]
Its a whitelist service, allows email to flow faster skipping greylisting. if you send spam you get removed from the whitelist then your emails get greylisted again. 

many orgs use this service (i think gmail, debian for sure) and most postfwd users

**Comment by gfa** [comment]
I've claimed the domain, we need to add this to the DNS records of autocrypt.org

```
_token._dnswl.autocrypt.org.		IN	TXT	"yo2q7kvxra3xiwwhenkm85fjhvrcxfuw"
```

**Comment by gfa** [comment]
Alternatively, emails were sent to postmaster@a.o and webmaster@a.o

**Comment by fschulze** [comment]
I added the token

**Comment by Valodim** [comment]
```
Hello,

as postmaster@dnswl.org I just notices your domain autocrypt.org has been registered at dnswl.org.
Unfortunately you where registered with an invalid e-mail address:

Reporting-MTA: dns; mail.dnswl.org
X-Postfix-Queue-ID: 3zT0vp0KkgzV
X-Postfix-Sender: rfc822; hostmaster+public/www-data@dnswl.org
Arrival-Date: Sat, 27 Jan 2018 04:03:17 +0100 (CET)

Final-Recipient: rfc822; hostmaster@autocrypt.org
Original-Recipient: rfc822;hostmaster@autocrypt.org
Action: failed
Status: 5.1.1
Remote-MTA: dns; mail.autocrypt.org
Diagnostic-Code: smtp; 550 5.1.1 <hostmaster@autocrypt.org>: Recipient address
    rejected: User unknown in local recipient table

maybe you could forward this to a responsible person.

Thanks
Andreas
```

**Comment by gfa** [comment]
@Valodim that wouldn't be necessary, I tried to validate the domain ownership sending an email to hostmaster@a.o alternatively to setting the DNS record.
The DNS record was faster.

Still doesn't show on the public interface of dnswl.org but autocrypt.org is already validated

**Comment by gfa** [comment]
This is done now

**Comment by litheu** [comment]
Hi. How / where do I get the TXT content for the _token._dnswl record please? How / where do I generate it? Thanks
