### ISSUE TITLE
Plan for IFF 2018

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#364]
We should document our plans for both the public Autocrypt session that will happen within the [internet freedom festival](https://internetfreedomfestival.org/) 2018 and the Autocrypt work sessions that will happen before or afterward.

For the work sessions, we might also want to contact the IFF organizers to see whether we can grab some space at Las Naves, but we will also likely have other locations we can work from.

**Comment by hpk42** [comment]
FTR, i am with xenia at elevate in Graz, Austria the days before IFF.  If i make it to IFF (unclear currently) i don't arrive before monday and probably leave on the saturday/sunday following it.

**Comment by kermoshina** [comment]
Hey @dkg ! I will be at IFF, and will be glad to propose help for any UX/UI sessions. 

Last time at CCC it worked pretty good in terms of scenarios: we had 3 groups according to the implementations ppl use or would like to test - k9, enigmail, delta.chat. We had ppl install Autocrypt following instructions from the website, then test it with their neighbours and then interoperability test b/w the 3 different implementations. To test the latter we had a task to add everyone to the same group chat. 

If we want to have a similar session (and I do think it is useful, as the audience will be less tech and we can get good feedback on UI/UX), would be great to have some burner email accounts for the testing. @Valodim @hpk42 @r10s @azul what do you think? 
My Ukrainian digisec trainer colleagues will also be present, and will be happy to join the session. 

The only important thing I would like to underline here: if we do a proper UX/UI workshop, we do not need to explain too much stuff before. And we must not explain anything to users, but gently observe and give assistance only if the situation is unblockable. Last time tech folks were giving away too much details before we even started to play around with implementations, and this impacted how people were perceiving the tool. 

So in terms of introduction to the session, I would honestly just give word to azul or vincent or dkg to talk about the mission of Autocrypt, but not about the design features of any of the implementations. People have to really figure it out themselves. 

In terms of keeping tracks of what was found during the session, I will personally use oldschool pen + paper kit, and type everything down after the session. We can also open a github issue for that, and may be some of the folks present at the session will contribute. However, we can not expect everyone to contribute to GitHub (even CCC folks did not do that much contributions, and the IFF audience is less used to GitHub).

**Comment by dkg** [comment]
@kermoshina thanks for the outline, this has been really useful in our planning here.  we've got an outline (on paper!) of what we're hoping to do, and we'll try to document it further soon.  there are several technical pieces that need to be pulled together, which we're working on.

**Comment by r10s** [comment]
@kermoshina thanks for pushing this forward. i am not on iff, but if i can help eg. with burner accounts, please let me know

**Comment by Valodim** [comment]
The event worked out really well! @kermoshina will be posting some results from the feedback we got on the mailing list soonish. thanks again to everyone who helped prepare the session! :+1:
