### ISSUE TITLE
FAQ needs to answer "Why not encrypt by default?"

### ISSUE THREAD

**Issue by lefherz** [autocrypt/autocrypt#366]
@valodim wanted to open an issue about writing a paragraph wrt "why not encrypt by default" into the FAQ. The question seems to come up quite often.

This issue is here to remind him of opening it.

**Comment by dkg** [comment]
I think we can be slightly less meta -- this issue can just document the need for that FAQ entry directly :)  @Valodim , if you (or anyone) writes a PR about this, feel free to reference this issue.
