### ISSUE TITLE
Unique naming of basic Autocrypt functions accross different MUAs

### ISSUE THREAD

**Issue by r10s** [autocrypt/autocrypt#368]
It might be useful to have unique names for basic Autocrypt functions that are visible in the UI. If different MUAs use the same wording at least for the basic titles, it seems much easier to explain things to the user.

Some basic functions visible in the UI are:
- a button that will send the Autocrypt Setup Message
- a button to switch prefer-encrypt=mutual on/off

There might be more, but these two seems to be a good start to deal with. If unique english names are found, we should take care the translations will also be unique (cmp [[Autocrypt] Should "Autocrypt Setup Message" be translated?](https://lists.mayfirst.org/pipermail/autocrypt/2018-February/000308.html)).

@dkg @Valodim @pbrunschwig @hpk42 ... There were several suggestions on [Enigmail](https://sourceforge.net/p/enigmail/bugs/749/), [Delta.Chat](https://github.com/deltachat/deltachat-android/issues/223) and on IRC, however, I think it is better to continue the discussion here at a central place.

**Comment by Valodim** [comment]
This is my current take on prefer-encrypt=mutual for K-9 Mail:

![image](https://user-images.githubusercontent.com/27813/36482918-f989cc22-1714-11e8-90bf-3673bb61c008.png)

I also think it would be a good feature of the spec to define language for some of the user-facing features. That way, users have labels for the concepts and can recognize and find them in different MUAs.

**Comment by r10s** [comment]
- in Delta Chat, the current wording for prefer-encrypt=mutual is "Prefer end-to-end-encryption"
- the current wording for sending the setup message is "Initiate Autocrypt Key Transfer" (taken from Enigmail), however, @pbrunschwig and i agree [here](https://github.com/deltachat/deltachat-android/issues/223#issuecomment-366760258) that the name "Initiate Autocrypt Setup Transfer" would probably be better. IMHO this is also nice because it does not introduce an additional term - "Initiate _Autocrypt Setup_ Transfer" results in an "_Autocrypt Setup_ Message" which sounds quite logic to me.

**Comment by pbrunschwig** [comment]
The "prefer encrypt" option in Enigmail is called "Prefer encrypted emails from the people you exchange email with."

**Comment by Valodim** [comment]
@pbrunschwig Related question, what does that checkmark currently do? Is there a plan for how it interacts with the other settings in enigmail?

**Comment by pbrunschwig** [comment]
You mean the checkmark for prefer-encrypt? It enables the "prefer-encrypt" part in the header. In my eyes, there is nothing more that this checkbox is currently meant for. 

However, Enigmail does respect the prefer-encrypt option when you write a message to a user from whom it has an Autocrypt header.

**Comment by dkg** [comment]
I also think it would be a good to define recommended language (in as
 many locales as we can afford) for some of the user-facing features.

We have few enough user-facing features that we might also want to ask a
graphic designer to consider whether any special iconography would be
useful to accompany those features, too.

Strongly encouraging a concrete recommendation should be a good value
proposition for implementers, as well:

 * They don't have to choose the wording
 * They have a better chance of users having already encountered the same
   terminology

**Comment by dkg** [comment]
@pbrunschwig wrote:
> You mean the checkmark for prefer-encrypt? It enables the "prefer-encrypt" part in the header. In my eyes, there is nothing more that this checkbox is currently meant for.

In addition to the emitted header, it should also set the internal `accounts[addr].prefer_encrypt` state, which is relevant also for calculating the Autocrypt recomendation.  right?

**Comment by pbrunschwig** [comment]
@dkg No, I don't think so. As you know, Enigmail already has a per-account setting for whether or not to encrypt messages by default. That value defines my own prefer-encrypt state for messages that I send.

If what you say were true, then I would not need a prefer-encrypt option for Autocrypt at all, but could simply imply that the per-account setting also defines what I want to receive from others.

**Comment by Valodim** [comment]
I wrote a blog post that summarizes my thoughts on prefer-encrypt=mutual: https://k9mail.github.io/2018/02/26/OpenPGP-Considerations-Part-III-Autocrypt.html

While this is written from a K-9 perspective, I think it echoes the core of Autocrypt, and we might want to elaborate on this point better in the spec itself.

I realize it is difficult to get in line with existing user expectations with Enigmail. However I consider it vital for the success of Autocrypt that clients that make use of our headers follow these parts of the spec as well, otherwise we effectively reduce it to "keys in headers".

**Comment by r10s** [comment]
@Valodim Great article, thank you for this, also the first two ones. So you are using "Autocrypt mutual mode" for the mutual-thingie? I can use this for Delta Chat [as well](https://github.com/deltachat/deltachat-android/issues/223#issuecomment-367530272) l then, it is definitely not the worst :) 

@pbrunschwig I can also understand the problems not to break the expectation with the existing Enigmail userbase. 
What is Enigmail doing if the user has not made a concrete setting for a peer? Maybe it is possible to set and use the internal `accounts[addr].prefer_encrypt` for these users then. Sth. like a three-state - On/Off/LetPeerDecide.

**Comment by pbrunschwig** [comment]
> What is Enigmail doing if the user has not made a concrete setting for a peer? Maybe it is possible to set and use the internal accounts[addr].prefer_encrypt for these users then. Sth. like a three-state - On/Off/LetPeerDecide.

@r10s If there is no concrete setting for a peer, then Enigmail will work as it did before Autocrypt. That is, it will follow the settings such as "encrypt by default" (which at the end represents the Enigmail `accounts[addr].prefer_encrypt` state) and the existing per-recipient rules.

**Comment by pbrunschwig** [comment]
I get the impression that you try to interpret something into Autocrypt in Enigmail that clashes with what is available today. In other words, Enigmail already has about 10 different settings that factor into the decision about whether or not to encrypt an email. I don't see a need to change these settings - at the end, these settings together represent the user's `prefer_encrypt` state.

The **only** reason I added an option for `prefer-encrypt` at sending time is to be compliant with the spec, saying that the default should be `off`, whereas the default in Enigmail would be `on` (unless a user changes the defaults).

**Comment by dkg** [comment]
The more i look at the k-9 screenshot, the more i like the text there.  Thanks for putting it out there, @Valodim !

i wonder if we could make it even shorter, though, or somehow collapse one of the paragraphs:

```
Autocrypt Mutual Mode [  ]

If the sender and all recipients have enabled mutual mode, encryption will be enabled by default.
[more info…]
```

and then if the `[more info…]` gets clicked, it could reveal:

```
If any of the parties don't have mutual mode enabled, then messages will be encrypted when the author explicitly chooses to encrypt, or when replying to an encrypted message.
```
