### ISSUE TITLE
manual PGP/MIME sig verification not working

### ISSUE THREAD

**Issue by bjacke** [autocrypt/autocrypt#375]
when "automatic decrypt/verify" is not enabled and if I want to verify a message which is PGP/MIME signed nothing happens. It's also not visible that the message is signed at all.

With "automatic decrypt/verify" enabled the message is being verified.

Tested on Linux with Ubuntu 18.04, TB 52.7 and 2.0.2 (20180411-1619) from amo.

**Comment by r10s** [comment]
I think your report is more Enigmail than Autocrypt related. Autocrypt is no app and has eg. no real user-interface; Autocrypt is a protocol that is implemented by different apps - eg. Enigmail.
So I think, your report should go to the Enigmail bug tracker which can be found at https://sourceforge.net/p/enigmail/bugs/

**Comment by pbrunschwig** [comment]
Yes, Enigmail won't necessarily tell you if a mail is signed or encrypted if automatic decryption is disabled. You can either use the menu Enigmail > Decrypt/Verify, or add the corresponding button to the toolbar. Apart from that, this is not Autocrypt-specific.

**Comment by bjacke** [comment]
you only replied to the second sentence, which was only a side note. The mail issue is in the first sentence and that is quite obviously a Enigmail bug: 'When "automatic decrypt/verify" is not enabled and if I want to verify a message which is PGP/MIME signed nothing happens'

This bug report should be reopened accordingly.

**Comment by bjacke** [comment]
sorry, missed r10s's comment about the wrong bug tracker. Sorry for the noise.
