### ISSUE TITLE
Autocrypt Setup Message Example uses AES-256, not AES-128

### ISSUE THREAD

**Issue by nwalfield** [autocrypt/autocrypt#390]
The [section on the ASM](https://autocrypt.org/level1.html#autocrypt-setup-message) says:

```
The symmetric encryption algorithm used MUST be AES-128.
```

But, [the example message ](https://autocrypt.org/level1.html#setup-message-example) is encrypted using AES-256.

**Comment by dkg** [comment]
I'd prefer that we change the documentation to say AES-256 than that we change the example message :)

**Comment by azul** [comment]
What are the implementations using?
I know we had successful exchange of ASM between some of them. So I expect there is some consistency.

**Comment by azul** [comment]
[Enigmail](https://gitlab.com/enigmail/enigmail/blob/master/package/autocrypt.jsm#L523) uses [openpgp.js to decrypt](https://openpgpjs.org/openpgpjs/doc/openpgp.js.html#line368).
The [decryption is handled by the message object](https://openpgpjs.org/openpgpjs/doc/message.js.html#line103) which extracts the first symmetrically encrypted packet and [decrypts it](https://openpgpjs.org/openpgpjs/doc/packet_symmetrically_encrypted.js.html#line80) using the algo used in the setup message. To me this looks like any algorithm would be decrypted fine.

On the [creation side](https://gitlab.com/enigmail/enigmail/blob/master/package/autocrypt.jsm#L398) it [uses the openpgp.js config settings for the encryption cipher](https://openpgpjs.org/openpgpjs/doc/message.js.html#line283).
