### ISSUE TITLE
Autocrypt-enabled MUA comparison table

### ISSUE THREAD

**Issue by lefherz** [autocrypt/autocrypt#395]
Hi, a coworker suggested that we added a list like this to the website, with autocrypt-enabled mail clients: https://en.wikipedia.org/wiki/Comparison_of_email_clients

The implementation status didn't suffice for him to find out what kind of client he could use, it has the wrong target group (developers, not users). 

Maybe we need to wait until more clients are 100% autocrypt compliant though. We could also display this with a percentage symbol, with a link to the implementation status table.

**Comment by ralphtheninja** [comment]
> Maybe we need to wait until more clients are 100% autocrypt compliant though.

I don't think we should wait. It's better to have a list that's incomplete, than no list at all :smile: Personally I'd like this information right now, since I don't know a lot about implementations other than Delta Chat.

**Comment by Valodim** [comment]
Even a status like "planned" with a link to the feature request would be helpful, maybe it'll encourage a +1 here or there :)

**Comment by hpk42** [comment]
we have the implementation status which is somewhat updated, reflects what we know and people submitted.
