### ISSUE TITLE
PDF of Released Spec points to v1.0.1 instead of 1.1

### ISSUE THREAD

**Issue by pbrunschwig** [autocrypt/autocrypt#400]
@Valodim released v1.1 of the spec, however the PDF provided is still v1.0.1.
@hpk42 can you fix this?

**Comment by hpk42** [comment]
to make a proper 1.1 release, fixing the web page but also
a mailing list post is neccessary and probably some cleanup. 
I had talked with vincent several times in december about
arranging together but right now (today, this week) is 
not good timing for me ...

**Comment by hpk42** [comment]
the pdf is fixed.
