### ISSUE TITLE
Suggest: independent Autocrypt proxy

### ISSUE THREAD

**Issue by datenbank-projekt** [autocrypt/autocrypt#406]
Hi,
I **suggest a tool that can be installed as a proxy which does autocrypt handling**: Encryption and decryption.
This way the user can use the regular email client. This communicates with the autocrypt-proxy and this pulls/pushes mails from/to the server as well as encryption/decryption.

Like this: Mailprogram -> Autocrypt-Proxy -> ... Internet ...

Two big advantages: 
a) Autocrypt (besser: it's use) becomes independent from single programs and vendors.
b) This would enable every mail to be encrypted BUT saved locally UNENCRYPTED and this transparent for future use (once downloaded to local storage).
This point is something I really dislike when using PGP: Mails stay encrypted on my system and - once I loose my key - I will be unable to read old (encrypted) mails. Using the proxy-setup this would be history,

Of course unencrypted local saving (=unencrypted transfer from proxy to local email software)  could be an optional setting in the proxy.

The proxy could have a similar setup as one need to set up spamihilator ( https://www.spamihilator.com/de/ ) which would also make cascading mail-proxies possible in a very easy way.

Olaf

**Comment by hpk42** [comment]
Personally i agree with you that removing pgp-encryption for local storage on an end point has lots of advantages.  This is also how delta-chat does it, the project i am involved in.  This specification/documentation repository is not actually about implementing software like an Autocrypt-proxy or Autocrypt clients.  A Proxy would be rather about IMAP and SMTP  that also implements Autocrypt and transparent encryption/decryption.  Without the proxy  being on localhost it'd violate end-to-end encryption.  I think there have bee projects (LEAP) and are projects (Protonmail?) that actually do have such a localhost daemon and dealing with encryption/decryption.  

In any case it's not really related to the spec and therefore closing this issue.
