### ISSUE TITLE
Storage of emails in clear text after decryption?

### ISSUE THREAD

**Issue by ghost** [autocrypt/autocrypt#426]
I think there is a question if email may be only encrypted on transfer, but not on local storage.

Meaning e.g. if a user receives an encrypted email, it would be decrypted and then stored in plain text by the MUA.

This way, the user can search in all emails and do not have to worry about losing keys that makes her unable to read old encrypted emails.

I did only find in Level 1 Spec this question touched en passant in chapter "Destroying Secret Key Material".

I guess this is a complicated question, e.g. when user opts-in to "store-only-decrypted", and replies to the decrypted stored email, the answer should be encrypted again etc.

I am missing some statement about this aspect in the documentation.

**Comment by user9209** [comment]
Maybe it would be good idea to add a chapter about best practices like the above "store-only-decrypted".

I would not insert "store-only-decrypted" directly to autocrypt as it can be implemented in different ways and security levels.

One possibility would be to say that all decrypted mails MUST be stored encrypted on the disk (with a symmetric key, e.g. the MUA login password, which also protects secret keys, imap and smtp credentials).

Removing the encryption will result in losing the signature and any manipulations on mails on client side will undetected.

It depends on the security level:
 - Decrypt all mails at runtime (best but slow)
 - Decrypt all mails and protect/encrypt them on disk (fast but loss of signatures)
 - Decrypt all mails and store them as normal mails (dangerous)

**Comment by wodry** [comment]
_"Protection against active adversaries (those which modify messages in transit) is the aim of future specifications."_ (https://autocrypt.org/level1.html)
When protection against active attacks in transit is not the aim of Level-1-Spec, I guess it's not Level-1-Spec's aim to protect against active attacks on received and (locally) stored data?
At least with POP3 received mails there is no passive mass surveillance possible (I do not know about IMAP, from my understanding the mails stay on someone else's computer, which I do not like and so did never hazzle around with it). RFC7435(Oportunistic Security) is really a new perspective, IMHO worth to think deeply about it.

Keep in mind: _"we want to avoid unreadable mail for users"_ (https://autocrypt.org/level1.html)

**Comment by wodry** [comment]
There is a 16 year old open bug in Thunderbird regarding exactly this: [
Encrypted email messages should be stored decrypted in the local folders
](https://bugzilla.mozilla.org/show_bug.cgi?id=280588)
