### ISSUE TITLE
Autocrypt spec still refers to "reset" state

### ISSUE THREAD

**Issue by link2xt** [autocrypt/autocrypt#428]
`reset` state has been removed, yet https://autocrypt.org/level1.html#updating-autocrypt-peer-state still referes to it:

> Messages SHOULD be ignored (i.e., peers[from-addr] SHOULD NOT be updated) in the following cases:
> - The content-type is `multipart/report`. In this case, it can be assumed the message was auto-generated. This avoids triggering a **reset** state from received Message Disposition Notifications (RFC 3798).

**Comment by link2xt** [comment]
Switching back to plaintext still relies on `reset` state https://autocrypt.org/examples.html#downgrading-switch-to-a-mua-without-autocrypt-support and Delta Chat has `reset` state in its implementation for this case.

Maybe `reset` state should instead be restored, not completely removed.

**Comment by dkg** [comment]
I think the `reset` state does not need to be explicitly specified -- this paragraph should be rewritten to describe the inferred/implicit property that you get from receiving mixed autocrypt/non-autocrypt mail.
