### ISSUE TITLE
Autocrypt headers with keydata should follow rfc2231 param encoding rules

### ISSUE THREAD

**Issue by mkmelin** [autocrypt/autocrypt#448]
As listed at https://autocrypt.org/level1.html#example-autocrypt-gossip-headers
```
Autocrypt: addr=alice@autocrypt.example; prefer-encrypt=mutual; keydata=
 mDMEXEcE6RYJKwYBBAHaRw8BAQdArjWwk3FAqyiFbFBKT4TzXcVBqPTB3gmzlC/Ub7O1u120F2F
 saWNlQGF1dG9jcnlwdC5leGFtcGxliJYEExYIAD4WIQTrhbtfozp14V6UTmPyMVUMT0fjjgUCXE
 cE6QIbAwUJA8JnAAULCQgHAgYVCgkICwIEFgIDAQIeAQIXgAAKCRDyMVUMT0fjjkqLAP9frlijw
 BJvA+HFnqCZcYIVxlyXzS5Gi5gMTpp37K73jgD/VbKYhkwk9iu689OYH4K7q7LbmdeaJ+RX88Y/
 ad9hZwy4OARcRwTpEgorBgEEAZdVAQUBAQdAQv8GIa2rSTzgqbXCpDDYMiKRVitCsy203x3sE9+
 eviIDAQgHiHgEGBYIACAWIQTrhbtfozp14V6UTmPyMVUMT0fjjgUCXEcE6QIbDAAKCRDyMVUMT0
 fjjlnQAQDFHUs6TIcxrNTtEZFjUFm1M0PJ1Dng/cDW4xN80fsn0QEA22Kr7VkCjeAEC08VSTeV+
 QFsmz55/lntWkwYWhmvOgE=
```

Using normal header parameter parsing for the keydata won't work (at least without clever hacks). 
Multiline parameter values need to be encoded as per rfc2231.
It would then look like something like
```
Autocrypt: addr=alice@autocrypt.example; prefer-encrypt=mutual; 
 keydata*0="xsDNBF2lnPIBDAC5cL9PQoQLTMuhjbYvb4Ncuuo0bfmgPRFywX53jPhoFf4Zg";
 keydata*1="6mv/seOXpgeccTdOcVttfzC8ycIKrt3aQTiwOG/ctaR4Bk/t6ayNFfdUNxHWk";
 keydata*2="4WCKzdz/56fW2O0F 23qIRd8UUJp5IIlN4RDdRCtdhVQIAuzvp2oVy/LaS2kx";

....

```

**Comment by hpk42** [comment]
When the current Autocrypt header was specified, we tested against 
various implementations and servers, and found no practical issues. 

https://www.rfc-editor.org/rfc/rfc822 in B.2 Semantics says: 

    "A line which continues a header field begins with a SPACE or
    HTAB  character,  while  a  line  beginning a field starts with a
    printable character which is not a colon."

In which way do you interpret RFC2231 as requiring a different format
than the one Autocrypt is using?
