### ISSUE TITLE
SSL certificate of autocrypt.org expired last night

### ISSUE THREAD

**Issue by jurgenhaas** [autocrypt/autocrypt#452]
Couldn't load the website this morning as the SSL cert has expired a couple of hours ago.

**Comment by missytake** [comment]
The current setup is a mess - for now, you can look at https://docs.autocrypt.org/, I'll try to fix the rest.

**Comment by jurgenhaas** [comment]
Thanks @missytake.

**Comment by missytake** [comment]
Fixed - while docs.autocrypt.org and www.autocrypt.org are hosted at readthedocs.io, this was not easily possible with autocrypt.org, so I pointed it to delta.chat and hosted a redirect there which points to docs.autocrypt.org.
