### ISSUE TITLE
Whitelist local recipients @mail.autocrypt.org

### ISSUE THREAD

**Issue by varac** [autocrypt/autocrypt#5]
atm, postfix will accept mails for all accounts on the server, we should restrict it to only accept mails for bot@

**Comment by hpk42** [comment]
i just tried and currently i get 454 relay access denied for both bot@autocrypt.org and for something@autocrypt.org

**Comment by hpk42** [comment]
but if you mean that root@mail.autocrypt.org e.g. should not be accepted then i'd suggest  "don't bother" and just allow postfix to accept mails for autocrypt.org proper.

**Comment by hpk42** [comment]
i configured it such that bot@autocrypt.org now works, thanks varac for the help.  I don't think there is any need to refine this further at the moment.
