### ISSUE TITLE
Gossip

### ISSUE THREAD

**Issue by Valodim** [autocrypt/autocrypt#53]
Hi there,

during discussions in April, one topic that came up was gossip. We had decided to put this on the backburner earlier, but it seems like there might be a good tradeoff there and I'd like to at least capture our thoughts.

The basic idea is that when Alice sends a message to Bob and Charlie, Bob might not be able to "reply all" if he doesn't have Charlie's key. What Alice can do is add Charlie's key to the mail - e.g. in an autocrypt header. We could simply allow keys for `to` parameters that don't match From and import these, but there are a couple of open questions:

- how rigid would we want such a mechanism to be? do we want to allow keys for any recipient from any sender? or just people who appear in Cc (can be spoofed)? just keys which the mail is also encrypted to (prevents hidden-recipients)?

- is there a use case besides group messaging? if there isn't, we could put the keys in the encrypted part of the message (memoryhole style)

- should the headers be included in replies, too? that increases size quite a bit, but if they aren't we can't be sure where replies to all might not work

**Comment by Valodim** [comment]
also very relevant: do we want this in L0? personally I find that is one of the biggest pains with encrypted mail at the moment, and group conversations regularly drop to plaintext because of this

**Comment by hpk42** [comment]
i tentatively think that it'd be good to have some form of gossipping in the spec -- the main question, i guess, is if we treat gossipped keys differently from a key matching the "from" which we might consider more authentic.  For py-autocrypt i want to keep all "seen keys" in a local append-only log, referencing message ids where a key came from -- so there is debuggability/discoverability of bad behaviour.

**Comment by Valodim** [comment]
Marking those keys can be done easily by overriding the preference we save anyways as "gossip". While using the keys in reply-all seems like a good idea, I would probably not honor a gossiped "preferencrypt=yes" in a new mail anyways.

In regards to my three points above:

1. any recipient actually seems fine, doesn't it? yes we can say "Cc only", but is there any advantage to that, if we are only going to use the key in reply-all anyways?
2. I don't think there is, so I would include the keys in the encrypted part of the message. This makes handling of encrypted messages slightly more complex, but protects metadata better.
3. Yes, we should include them in replies. We can cut corners later if we find it's possible, but for a first iteration I wouldn't try to be clever here to save a few kb.
