### ISSUE TITLE
redirect https://autocrypt.org/ to https://autocrypt.readthedocs.io

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#6]
Could someone with access to the domain set up an http and https service on `autocrypt.org` and have it send HTTP 302 redirects to https://autocrypt.readthedocs.io ?

**Comment by varac** [comment]
mostly done except that we need to add `autocrpyt.org` as an SAN to the LE cert.
But currently I'm blocked by current domain foo.

**Comment by dkg** [comment]
the domain foo should now be resolved so you should be unblocked.  Thanks for sorting this out, varac!

I note that http://autocrypt.org/ currently says:

```
400 Bad Request
The plain HTTP request was sent to HTTPS port
```

**Comment by varac** [comment]
ok, fixed
