### ISSUE TITLE
Some Background on Forward Error Correction to Correct Transcription Errors

### ISSUE THREAD

**Issue by nwalfield** [autocrypt/autocrypt#61]
When a user needs to transcribe some data, e.g., the automatically generated passphrase used when transferring a secret key between two devices, it may be useful to have forward error correction (FEC) to correct some transcription errors.

Note: a simple FEC is used to detect transcription errors for IBANs, which has reduce routing errors by about 99.9% [1].  The FEC technique used in IBANs is very simple, but it only detects errors and doesn't correct them.  In this particular context, this is probably sufficient.

There are a bunch of different techniques, but given that autocrypt will be implemented many times, it is probably best to use something simple.

One popular FEC was described by Luigi Rizzo in [2].  A 2-clause BSD-licensed implementation accompanied the paper [3,4].  Rizzo describes the algorithm as simple and it only requires about 300 lines of C code (according to sloccount).  The code has been adopted by several projects include Tahoe-LAFS who provide a GPL-licensed improved version with Python and Haskell bindings [5].  According to Zooko [5], fecpp provides a BSD-based bit-compatible implementation [6].  There is apparently also a Java version [7].

[1] https://en.wikipedia.org/wiki/International_Bank_Account_Number
[2] http://pages.cs.wisc.edu/~suman/courses/740/papers/rizzo97ccr.pdf
[3] http://info.iet.unipi.it/~luigi/fec.html
[4] http://info.iet.unipi.it/~luigi/vdm98/vdm980702.tgz
[5] https://github.com/tahoe-lafs/zfec
[6] https://www.randombit.net/code/fecpp/
[7] http://jamesclarke.net/notes/javafec

**Comment by RokerHRO** [comment]
If I understand the paper correctly, the encoding works only if the transmission has the following properties:
1. the packets have a number/ID (e.g. 0 ... n). Sender & receiver know this 'n' and the number of redundancy packets 'k'.
2. a packet is received either correctly or not at all
3. the receiver knows which packets it got, which are lost during transmission.
So the receiver can recover the lost packets from the received packets (if the number of lost packets is smaller than the number of "redundancy" packets the sender added before).
That is not the case if a passphrase "correct horse battery staple" is mutilated into "collect hoarse battery staple". Of course, there are error-correcting codes that works also when the receiver does _not_ know which data is corrupt, but these codes require even more redundancy in the data. Even 1-bit error correction, e.h. the (7,4) Hamming code nearly double the length of the data. The BCH(15,7,4) code is able to correct 2-bit errors, but more than double the data size.

**Comment by Valodim** [comment]
Closing this issue as stale. It's an interesting thought, but not a priority right now
