### ISSUE TITLE
What if prefer-encrypt is set to an unknown value?

### ISSUE THREAD

**Issue by r10s** [autocrypt/autocrypt#64]
What if prefer-encrypt is set to an unknown value?

- Ignore autocrypt header (as for unknown attribute names not starting with and underscore)?
- Use autocrypt header and assume prefer-encrypt to be unset?

**Comment by Valodim** [comment]
the conservative option of falling back to nopreference seems fine to me

**Comment by dkg** [comment]
Agreed.  I'm working on a pull request for this.
