### ISSUE TITLE
Shouldn't we support multiple secret keys in the "Autocrypt Setup Message"?

### ISSUE THREAD

**Issue by r10s** [autocrypt/autocrypt#65]
If the user has more than one secret keys on Device A (eg. one for reading old mails and a newer one) and wants to use autocrypt on the Device B,  all keys should be transferred.

**Comment by dkg** [comment]
In the discussion today, i think we reached a rough consensus that for level 0, we want to deal with a single OpenPGP certificate (a 2048-bit RSA primary key for signing/certifying and a 2048-bit RSA subkey for encryption) for the Autocrypt Setup Message.  As long as we have a mechanism for creating a new kind of setup message, or for storing arbitrary stuff elsewhere in the message, we can experiment later for use cases where people end up with multiple secret keys.  but it doesn't sound like this is part of the level 0 spec.

**Comment by azul** [comment]
#48 has a lengthy explanation about an earlier multi key support discussion.

**Comment by r10s** [comment]
okay, I'm fine on this.
