### ISSUE TITLE
"state" might be too generic of a variable name

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#68]
the autocrypt peer state (as of the merge of #62) currently includes a variable named `state`, which is a mix of the "prefer-encrypt" information and the reset.  can we pick a better name than "state" ?

**Comment by juga0** [comment]
We also have all sort of states with maybe not uniform nomenclature, as can be seen in the glossary: https://github.com/autocrypt/autocrypt/pull/151/commits/f70ecc9c7901b69750f2f13247924237971157d5#diff-bf5c4a375247983f5d09b8360467f5dfR30

**Comment by dkg** [comment]
@nwalfield suggests "disposition"

**Comment by azul** [comment]
@hpk42 suggested 'recommendation input'

Here's a fairly radical idea...
* remove the reset state and check if last_seen > last_seen_autocrypt instead
* rename to prefer_encrypt and store the state from the last ac header
* store nothing in it if received through gossip

Would the behaviour be the same?

**Comment by r10s** [comment]
@hpk42 and me also thought about `keystate` yesterday

**Comment by dkg** [comment]
I note that resolving #202 would remove the term `state` from many other places in the document.  I don't think that using the term `state` as in `peer[alice@example.org].state` is particularly problematic if the word `state` isn't used to mean anything else.  So if #202 is resolved by a successful merge one way or the other, i think this issue can also be closed.

**Comment by azul** [comment]
#204 superseeded #202

**Comment by Valodim** [comment]
obsolete with #204
