### ISSUE TITLE
assumptions about MUAs storing date about message receipt

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#70]
The current definition of "effective date" of a message assumes that a mail client is capable of tracking "first receipt" of a message.  Some MUAs might not be able to do that.

One proposal is to say that a MUA can choose one of two options.  When a message is seen with a missing or future date, either:
 * store an "effective date" associated with that message, or return the previously-stored "effective date"
or
 * treat the message as having no valid Autocrypt headers.

The problem this addresses is a single forged or mistaken message with no date or a future date that is regularly re-ingested by a stateless client can permanently reset or override legitimate autocrypt-transported key material.

**Comment by dkg** [comment]
There was a previous note about it that has since been removed for cleanliness:
```
-   This implies that Autocrypt clients keep track of whether they have
-   encountered a given message before, but does not provide them with
-   guidance on how to do so.  :mailheader:`Message-ID`?  Digest of
-   full message body?  The consequences of re-triggering the message
-   receipt process should only matter for messages that are
-   erroneously marked with a future date. Another approach that would
-   not require keeping track of the message would be to simply ignore
-   messages whose :mailheader:`Date:` header is in the future.
```

**Comment by Valodim** [comment]
Those messages are pretty much an error case to begin with. I think it's fine for a client that can't track first receipt of a message to just consider it invalid for autocrypt processing.
