### ISSUE TITLE
either redirect or destroy inbome.readthedocs.io

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#8]
https://inbome.readthedocs.io still exists and is clearly out of date.  

@hpk42, i think you might have set it up in the first place.  could you ensure that it either redirects to https://autocrypt.readthedocs.io, or that it is completely destroyed?

**Comment by hpk42** [comment]
http://inbome.readthedocs.io/en/latest/ now tells to use autocrypt.
