### ISSUE TITLE
motivate prefer-encrypt=mutual

### ISSUE THREAD

**Issue by dkg** [autocrypt/autocrypt#90]
prefer-encrypt=mutual seems to be weaker than prefer-encrypt=yes.

why did we switch to it?

 * the problem cases arise with situations where peers have different preferences
 * moving the initial encrypted message from one peer to the other doesn't actually resolve the preference mismatch, it just results in surprisingly unreadable mail one hop later in the conversation.
 * surprisingly unreadable mail is likely to create pushback from the party with the weaker preferences, possibly in the form of "please don't send me encrypted mail" messages, which is a strong social pressure against encrypted messages.

**Comment by dkg** [comment]
This rationale ought to be documented somewhere in the spec.

**Comment by Valodim** [comment]
Seems to me the "prefer-encrypt=yes" idea is mostly of historical interest at this point. How many paragraphs would we want to spend in the spec to describe and immediately discard it?

Maybe having this in a discarded ideas or Q&A document suffices? We probably have a bunch of other ideas that would be well placed there
